-- GENERATED by ZRC.SeedImporter. Do not hand-edit; re-run the importer on workbook updates.
-- Source: docs/zaara_royal_catering_menu.xlsx (122 item rows, 16 packages).
-- Idempotent: re-deploying changes nothing.

MERGE INTO [catalog].[Categories] AS t
USING (VALUES
    (N'Breakfast', N'breakfast', 10, 1),
    (N'Lunch', N'lunch', 20, 1),
    (N'Dinner', N'dinner', 30, 1),
    (N'Corporate Program', N'corporate-program', 40, 1),
    (N'House Party', N'house-party', 50, 1)
) AS s ([Name], [Slug], [SortOrder], [IsActive])
ON t.[Name] = s.[Name]
WHEN MATCHED THEN UPDATE SET [Slug] = s.[Slug], [SortOrder] = s.[SortOrder], [IsActive] = s.[IsActive], [UpdatedAt] = SYSUTCDATETIME()
WHEN NOT MATCHED THEN INSERT ([Name], [Slug], [SortOrder], [IsActive]) VALUES (s.[Name], s.[Slug], s.[SortOrder], s.[IsActive]);
GO

MERGE INTO [catalog].[Items] AS t
USING (VALUES
    (N'Paratha (2 pcs)', 1),
    (N'Vegetable Bhaji', 1),
    (N'Scrambled Egg', 1),
    (N'Chola Dal', 1),
    (N'Sweet', 1),
    (N'Black Tea', 1),
    (N'Luchi or Paratha', 1),
    (N'Aloo Dum', 1),
    (N'Egg Curry', 1),
    (N'Boot Dal', 1),
    (N'Semolina Halwa', 1),
    (N'Seasonal Fruit', 1),
    (N'Doi-Chira (Yogurt & Flattened Rice)', 1),
    (N'Tea / Coffee', 1),
    (N'Bhuna Khichuri', 1),
    (N'Beef Bhuna', 1),
    (N'Fried Eggplant', 1),
    (N'Borhani', 1),
    (N'Salad', 1),
    (N'Jilapi / Sweet', 1),
    (N'White Rice', 1),
    (N'Chicken Curry', 1),
    (N'Masoor Dal', 1),
    (N'Mixed Vegetables', 1),
    (N'Aloo Bhorta (Mashed Potato)', 1),
    (N'Pickle', 1),
    (N'Rice / Polao', 1),
    (N'Chicken Roast', 1),
    (N'Fried Rui Fish', 1),
    (N'Dal', 1),
    (N'Vegetables', 1),
    (N'Sweet Yogurt', 1),
    (N'Paan-Supari', 1),
    (N'Kacchi Biryani (Mutton/Chicken)', 1),
    (N'Egg', 1),
    (N'Shahi Zarda', 1),
    (N'Polao', 1),
    (N'Chicken Rezala', 1),
    (N'Beef Rezala', 1),
    (N'Hilsa / Rui Fish', 1),
    (N'Firni', 1),
    (N'Morog Polao / Kacchi', 1),
    (N'Beef Kala Bhuna', 1),
    (N'Mutton Rezala', 1),
    (N'Fried Fish', 1),
    (N'Shahi Tukra', 1),
    (N'Fruit Platter', 1),
    (N'Samosa', 1),
    (N'Singara', 1),
    (N'Chicken Pakora', 1),
    (N'Biscuits', 1),
    (N'Water', 1),
    (N'Polao / Rice', 1),
    (N'Mineral Water', 1),
    (N'Rice & Polao', 1),
    (N'2 Chicken & Beef Dishes', 1),
    (N'Fish', 1),
    (N'Salad Bar', 1),
    (N'Dessert', 1),
    (N'Soft Drink', 1),
    (N'Kacchi / Biryani', 1),
    (N'Roast', 1),
    (N'Kebab Station', 1),
    (N'Soup', 1),
    (N'Beverages', 1),
    (N'Tea/Coffee Corner', 1),
    (N'Chicken Fry', 1),
    (N'Shawarma / Roll', 1),
    (N'Fuchka / Chotpoti', 1),
    (N'French Fries', 1),
    (N'Spring Roll', 1),
    (N'Fish Fry', 1),
    (N'Chicken / Beef BBQ', 1),
    (N'Grilled Kebab', 1),
    (N'Naan', 1),
    (N'Dip Sauce', 1)
) AS s ([Name], [IsActive])
ON t.[Name] = s.[Name]
WHEN MATCHED THEN UPDATE SET [IsActive] = s.[IsActive], [UpdatedAt] = SYSUTCDATETIME()
WHEN NOT MATCHED THEN INSERT ([Name], [IsActive]) VALUES (s.[Name], s.[IsActive]);
GO

MERGE INTO [catalog].[AddOns] AS t
USING (VALUES
    (N'Outdoor Setup', N'Outdoor setup for BBQ / house parties (admin must set price)', N'Flat', 0, 0, 0),
    (N'Live Chef Service', N'Live chef service for BBQ / house parties (admin must set price)', N'PerHead', 0, 0, 0)
) AS s ([Name], [Description], [PricingType], [Price], [Cost], [IsActive])
ON t.[Name] = s.[Name]
WHEN MATCHED THEN UPDATE SET [Description] = s.[Description], [PricingType] = s.[PricingType], [UpdatedAt] = SYSUTCDATETIME()
WHEN NOT MATCHED THEN INSERT ([Name], [Description], [PricingType], [Price], [Cost], [IsActive]) VALUES (s.[Name], s.[Description], s.[PricingType], s.[Price], s.[Cost], s.[IsActive]);
GO

MERGE INTO [catalog].[Packages] AS t
USING (VALUES
    (N'Breakfast', N'Classic Breakfast', N'breakfast-classic-breakfast', NULL, 120.00, 1, 10, 0, 1),
    (N'Breakfast', N'Premium Breakfast', N'breakfast-premium-breakfast', NULL, 180.00, 1, 20, 0, 1),
    (N'Breakfast', N'Royal Breakfast', N'breakfast-royal-breakfast', NULL, 250.00, 1, 30, 0, 1),
    (N'Lunch', N'Standard', N'lunch-standard', NULL, 250.00, 1, 40, 0, 1),
    (N'Lunch', N'Premium', N'lunch-premium', NULL, 350.00, 1, 50, 0, 1),
    (N'Lunch', N'Royal Kacchi', N'lunch-royal-kacchi', NULL, 500.00, 1, 60, 0, 1),
    (N'Dinner', N'Standard', N'dinner-standard', NULL, 280.00, 1, 70, 0, 1),
    (N'Dinner', N'Premium', N'dinner-premium', NULL, 400.00, 1, 80, 0, 1),
    (N'Dinner', N'Royal Dinner', N'dinner-royal-dinner', NULL, 550.00, 1, 90, 0, 1),
    (N'Corporate Program', N'Snacks / Tea Break Package', N'corporate-program-snacks-tea-break-package', N'Ideal for morning or afternoon meeting breaks', 80.00, 1, 100, 0, 1),
    (N'Corporate Program', N'Box Lunch', N'corporate-program-box-lunch', NULL, 220.00, 1, 110, 0, 1),
    (N'Corporate Program', N'Standard Buffet', N'corporate-program-standard-buffet', NULL, 380.00, 40, 120, 0, 1),
    (N'Corporate Program', N'Executive Buffet', N'corporate-program-executive-buffet', NULL, 550.00, 1, 130, 0, 1),
    (N'House Party', N'Snacks Party', N'house-party-snacks-party', NULL, 200.00, 1, 140, 0, 1),
    (N'House Party', N'Full Dinner Party', N'house-party-full-dinner-party', NULL, 420.00, 1, 150, 0, 1),
    (N'House Party', N'BBQ Night', N'house-party-bbq-night', N'Outdoor setup & live chef service available (extra charges apply)', 650.00, 1, 160, 0, 1)
) AS s ([CategoryName], [Name], [Slug], [Tagline], [SalePricePerHead], [MinGuests], [SortOrder], [IsFeatured], [IsActive])
ON t.[Slug] = s.[Slug]
WHEN MATCHED THEN UPDATE SET [CategoryId] = (SELECT [Id] FROM [catalog].[Categories] WHERE [Name] = s.[CategoryName]),
    [Name] = s.[Name], [Tagline] = s.[Tagline], [SalePricePerHead] = s.[SalePricePerHead], [MinGuests] = s.[MinGuests],
    [SortOrder] = s.[SortOrder], [IsActive] = s.[IsActive], [UpdatedAt] = SYSUTCDATETIME()
WHEN NOT MATCHED THEN INSERT ([CategoryId], [Name], [Slug], [Tagline], [SalePricePerHead], [MinGuests], [SortOrder], [IsFeatured], [IsActive])
    VALUES ((SELECT [Id] FROM [catalog].[Categories] WHERE [Name] = s.[CategoryName]), s.[Name], s.[Slug], s.[Tagline], s.[SalePricePerHead], s.[MinGuests], s.[SortOrder], s.[IsFeatured], s.[IsActive]);
GO

-- PackageItems: full replace (cost lives on the link).
DELETE pi FROM [catalog].[PackageItems] pi
JOIN [catalog].[Packages] p ON p.[Id] = pi.[PackageId] WHERE p.[Slug] IN (N'breakfast-classic-breakfast', N'breakfast-premium-breakfast', N'breakfast-royal-breakfast', N'lunch-standard', N'lunch-premium', N'lunch-royal-kacchi', N'dinner-standard', N'dinner-premium', N'dinner-royal-dinner', N'corporate-program-snacks-tea-break-package', N'corporate-program-box-lunch', N'corporate-program-standard-buffet', N'corporate-program-executive-buffet', N'house-party-snacks-party', N'house-party-full-dinner-party', N'house-party-bbq-night');
INSERT INTO [catalog].[PackageItems] ([PackageId], [ItemId], [CostPerHead], [DisplayName], [SortOrder]) VALUES
    ((SELECT [Id] FROM [catalog].[Packages] WHERE [Slug] = N'breakfast-classic-breakfast'), (SELECT [Id] FROM [catalog].[Items] WHERE [Name] = N'Paratha (2 pcs)'), 20.00, N'Paratha (2 pcs)', 10),
    ((SELECT [Id] FROM [catalog].[Packages] WHERE [Slug] = N'breakfast-classic-breakfast'), (SELECT [Id] FROM [catalog].[Items] WHERE [Name] = N'Vegetable Bhaji'), 10.00, N'Vegetable Bhaji', 20),
    ((SELECT [Id] FROM [catalog].[Packages] WHERE [Slug] = N'breakfast-classic-breakfast'), (SELECT [Id] FROM [catalog].[Items] WHERE [Name] = N'Scrambled Egg'), 10.00, N'Scrambled Egg', 30),
    ((SELECT [Id] FROM [catalog].[Packages] WHERE [Slug] = N'breakfast-classic-breakfast'), (SELECT [Id] FROM [catalog].[Items] WHERE [Name] = N'Chola Dal'), 10.00, N'Chola Dal', 40),
    ((SELECT [Id] FROM [catalog].[Packages] WHERE [Slug] = N'breakfast-classic-breakfast'), (SELECT [Id] FROM [catalog].[Items] WHERE [Name] = N'Sweet'), 10.00, N'Sweet', 50),
    ((SELECT [Id] FROM [catalog].[Packages] WHERE [Slug] = N'breakfast-classic-breakfast'), (SELECT [Id] FROM [catalog].[Items] WHERE [Name] = N'Black Tea'), 10.00, N'Black Tea', 60),
    ((SELECT [Id] FROM [catalog].[Packages] WHERE [Slug] = N'breakfast-premium-breakfast'), (SELECT [Id] FROM [catalog].[Items] WHERE [Name] = N'Luchi or Paratha'), 25.00, N'Luchi or Paratha', 10),
    ((SELECT [Id] FROM [catalog].[Packages] WHERE [Slug] = N'breakfast-premium-breakfast'), (SELECT [Id] FROM [catalog].[Items] WHERE [Name] = N'Aloo Dum'), 15.00, N'Aloo Dum', 20),
    ((SELECT [Id] FROM [catalog].[Packages] WHERE [Slug] = N'breakfast-premium-breakfast'), (SELECT [Id] FROM [catalog].[Items] WHERE [Name] = N'Egg Curry'), 15.00, N'Egg Curry', 30),
    ((SELECT [Id] FROM [catalog].[Packages] WHERE [Slug] = N'breakfast-premium-breakfast'), (SELECT [Id] FROM [catalog].[Items] WHERE [Name] = N'Boot Dal'), 10.00, N'Boot Dal', 40),
    ((SELECT [Id] FROM [catalog].[Packages] WHERE [Slug] = N'breakfast-premium-breakfast'), (SELECT [Id] FROM [catalog].[Items] WHERE [Name] = N'Semolina Halwa'), 15.00, N'Semolina Halwa', 50),
    ((SELECT [Id] FROM [catalog].[Packages] WHERE [Slug] = N'breakfast-premium-breakfast'), (SELECT [Id] FROM [catalog].[Items] WHERE [Name] = N'Seasonal Fruit'), 10.00, N'Seasonal Fruit', 60),
    ((SELECT [Id] FROM [catalog].[Packages] WHERE [Slug] = N'breakfast-premium-breakfast'), (SELECT [Id] FROM [catalog].[Items] WHERE [Name] = N'Doi-Chira (Yogurt & Flattened Rice)'), 10.00, N'Doi-Chira (Yogurt & Flattened Rice)', 70),
    ((SELECT [Id] FROM [catalog].[Packages] WHERE [Slug] = N'breakfast-premium-breakfast'), (SELECT [Id] FROM [catalog].[Items] WHERE [Name] = N'Tea / Coffee'), 5.00, N'Tea / Coffee', 80),
    ((SELECT [Id] FROM [catalog].[Packages] WHERE [Slug] = N'breakfast-royal-breakfast'), (SELECT [Id] FROM [catalog].[Items] WHERE [Name] = N'Bhuna Khichuri'), 30.00, N'Bhuna Khichuri', 10),
    ((SELECT [Id] FROM [catalog].[Packages] WHERE [Slug] = N'breakfast-royal-breakfast'), (SELECT [Id] FROM [catalog].[Items] WHERE [Name] = N'Beef Bhuna'), 50.00, N'Beef Bhuna', 20),
    ((SELECT [Id] FROM [catalog].[Packages] WHERE [Slug] = N'breakfast-royal-breakfast'), (SELECT [Id] FROM [catalog].[Items] WHERE [Name] = N'Egg Curry'), 15.00, N'Egg Curry', 30),
    ((SELECT [Id] FROM [catalog].[Packages] WHERE [Slug] = N'breakfast-royal-breakfast'), (SELECT [Id] FROM [catalog].[Items] WHERE [Name] = N'Fried Eggplant'), 10.00, N'Fried Eggplant', 40),
    ((SELECT [Id] FROM [catalog].[Packages] WHERE [Slug] = N'breakfast-royal-breakfast'), (SELECT [Id] FROM [catalog].[Items] WHERE [Name] = N'Borhani'), 15.00, N'Borhani', 50),
    ((SELECT [Id] FROM [catalog].[Packages] WHERE [Slug] = N'breakfast-royal-breakfast'), (SELECT [Id] FROM [catalog].[Items] WHERE [Name] = N'Salad'), 5.00, N'Salad', 60),
    ((SELECT [Id] FROM [catalog].[Packages] WHERE [Slug] = N'breakfast-royal-breakfast'), (SELECT [Id] FROM [catalog].[Items] WHERE [Name] = N'Jilapi / Sweet'), 15.00, N'Jilapi / Sweet', 70),
    ((SELECT [Id] FROM [catalog].[Packages] WHERE [Slug] = N'breakfast-royal-breakfast'), (SELECT [Id] FROM [catalog].[Items] WHERE [Name] = N'Tea / Coffee'), 5.00, N'Tea / Coffee', 80),
    ((SELECT [Id] FROM [catalog].[Packages] WHERE [Slug] = N'lunch-standard'), (SELECT [Id] FROM [catalog].[Items] WHERE [Name] = N'White Rice'), 20.00, N'White Rice', 10),
    ((SELECT [Id] FROM [catalog].[Packages] WHERE [Slug] = N'lunch-standard'), (SELECT [Id] FROM [catalog].[Items] WHERE [Name] = N'Chicken Curry'), 75.00, N'Chicken Curry', 20),
    ((SELECT [Id] FROM [catalog].[Packages] WHERE [Slug] = N'lunch-standard'), (SELECT [Id] FROM [catalog].[Items] WHERE [Name] = N'Masoor Dal'), 15.00, N'Masoor Dal', 30),
    ((SELECT [Id] FROM [catalog].[Packages] WHERE [Slug] = N'lunch-standard'), (SELECT [Id] FROM [catalog].[Items] WHERE [Name] = N'Mixed Vegetables'), 15.00, N'Mixed Vegetables', 40),
    ((SELECT [Id] FROM [catalog].[Packages] WHERE [Slug] = N'lunch-standard'), (SELECT [Id] FROM [catalog].[Items] WHERE [Name] = N'Aloo Bhorta (Mashed Potato)'), 10.00, N'Aloo Bhorta (Mashed Potato)', 50),
    ((SELECT [Id] FROM [catalog].[Packages] WHERE [Slug] = N'lunch-standard'), (SELECT [Id] FROM [catalog].[Items] WHERE [Name] = N'Salad'), 5.00, N'Salad', 60),
    ((SELECT [Id] FROM [catalog].[Packages] WHERE [Slug] = N'lunch-standard'), (SELECT [Id] FROM [catalog].[Items] WHERE [Name] = N'Pickle'), 5.00, N'Pickle', 70),
    ((SELECT [Id] FROM [catalog].[Packages] WHERE [Slug] = N'lunch-premium'), (SELECT [Id] FROM [catalog].[Items] WHERE [Name] = N'Rice / Polao'), 25.00, N'Rice / Polao', 10),
    ((SELECT [Id] FROM [catalog].[Packages] WHERE [Slug] = N'lunch-premium'), (SELECT [Id] FROM [catalog].[Items] WHERE [Name] = N'Chicken Roast'), 50.00, N'Chicken Roast', 20),
    ((SELECT [Id] FROM [catalog].[Packages] WHERE [Slug] = N'lunch-premium'), (SELECT [Id] FROM [catalog].[Items] WHERE [Name] = N'Beef Bhuna'), 60.00, N'Beef Bhuna', 30),
    ((SELECT [Id] FROM [catalog].[Packages] WHERE [Slug] = N'lunch-premium'), (SELECT [Id] FROM [catalog].[Items] WHERE [Name] = N'Fried Rui Fish'), 35.00, N'Fried Rui Fish', 40),
    ((SELECT [Id] FROM [catalog].[Packages] WHERE [Slug] = N'lunch-premium'), (SELECT [Id] FROM [catalog].[Items] WHERE [Name] = N'Dal'), 10.00, N'Dal', 50),
    ((SELECT [Id] FROM [catalog].[Packages] WHERE [Slug] = N'lunch-premium'), (SELECT [Id] FROM [catalog].[Items] WHERE [Name] = N'Vegetables'), 10.00, N'Vegetables', 60),
    ((SELECT [Id] FROM [catalog].[Packages] WHERE [Slug] = N'lunch-premium'), (SELECT [Id] FROM [catalog].[Items] WHERE [Name] = N'Salad'), 5.00, N'Salad', 70),
    ((SELECT [Id] FROM [catalog].[Packages] WHERE [Slug] = N'lunch-premium'), (SELECT [Id] FROM [catalog].[Items] WHERE [Name] = N'Sweet Yogurt'), 5.00, N'Sweet Yogurt', 80),
    ((SELECT [Id] FROM [catalog].[Packages] WHERE [Slug] = N'lunch-premium'), (SELECT [Id] FROM [catalog].[Items] WHERE [Name] = N'Paan-Supari'), 5.00, N'Paan-Supari', 90),
    ((SELECT [Id] FROM [catalog].[Packages] WHERE [Slug] = N'lunch-royal-kacchi'), (SELECT [Id] FROM [catalog].[Items] WHERE [Name] = N'Kacchi Biryani (Mutton/Chicken)'), 205.00, N'Kacchi Biryani (Mutton/Chicken)', 10),
    ((SELECT [Id] FROM [catalog].[Packages] WHERE [Slug] = N'lunch-royal-kacchi'), (SELECT [Id] FROM [catalog].[Items] WHERE [Name] = N'Borhani'), 25.00, N'Borhani', 20),
    ((SELECT [Id] FROM [catalog].[Packages] WHERE [Slug] = N'lunch-royal-kacchi'), (SELECT [Id] FROM [catalog].[Items] WHERE [Name] = N'Salad'), 10.00, N'Salad', 30),
    ((SELECT [Id] FROM [catalog].[Packages] WHERE [Slug] = N'lunch-royal-kacchi'), (SELECT [Id] FROM [catalog].[Items] WHERE [Name] = N'Egg'), 15.00, N'Egg', 40),
    ((SELECT [Id] FROM [catalog].[Packages] WHERE [Slug] = N'lunch-royal-kacchi'), (SELECT [Id] FROM [catalog].[Items] WHERE [Name] = N'Fried Eggplant'), 10.00, N'Fried Eggplant', 50),
    ((SELECT [Id] FROM [catalog].[Packages] WHERE [Slug] = N'lunch-royal-kacchi'), (SELECT [Id] FROM [catalog].[Items] WHERE [Name] = N'Shahi Zarda'), 20.00, N'Shahi Zarda', 60),
    ((SELECT [Id] FROM [catalog].[Packages] WHERE [Slug] = N'lunch-royal-kacchi'), (SELECT [Id] FROM [catalog].[Items] WHERE [Name] = N'Sweet'), 10.00, N'Sweet', 70),
    ((SELECT [Id] FROM [catalog].[Packages] WHERE [Slug] = N'lunch-royal-kacchi'), (SELECT [Id] FROM [catalog].[Items] WHERE [Name] = N'Paan-Supari'), 5.00, N'Paan-Supari', 80),
    ((SELECT [Id] FROM [catalog].[Packages] WHERE [Slug] = N'dinner-standard'), (SELECT [Id] FROM [catalog].[Items] WHERE [Name] = N'Polao'), 25.00, N'Polao', 10),
    ((SELECT [Id] FROM [catalog].[Packages] WHERE [Slug] = N'dinner-standard'), (SELECT [Id] FROM [catalog].[Items] WHERE [Name] = N'Chicken Rezala'), 90.00, N'Chicken Rezala', 20),
    ((SELECT [Id] FROM [catalog].[Packages] WHERE [Slug] = N'dinner-standard'), (SELECT [Id] FROM [catalog].[Items] WHERE [Name] = N'Dal'), 15.00, N'Dal', 30),
    ((SELECT [Id] FROM [catalog].[Packages] WHERE [Slug] = N'dinner-standard'), (SELECT [Id] FROM [catalog].[Items] WHERE [Name] = N'Vegetables'), 15.00, N'Vegetables', 40),
    ((SELECT [Id] FROM [catalog].[Packages] WHERE [Slug] = N'dinner-standard'), (SELECT [Id] FROM [catalog].[Items] WHERE [Name] = N'Salad'), 5.00, N'Salad', 50),
    ((SELECT [Id] FROM [catalog].[Packages] WHERE [Slug] = N'dinner-standard'), (SELECT [Id] FROM [catalog].[Items] WHERE [Name] = N'Pickle'), 5.00, N'Pickle', 60),
    ((SELECT [Id] FROM [catalog].[Packages] WHERE [Slug] = N'dinner-standard'), (SELECT [Id] FROM [catalog].[Items] WHERE [Name] = N'Sweet'), 10.00, N'Sweet', 70),
    ((SELECT [Id] FROM [catalog].[Packages] WHERE [Slug] = N'dinner-premium'), (SELECT [Id] FROM [catalog].[Items] WHERE [Name] = N'Polao'), 30.00, N'Polao', 10),
    ((SELECT [Id] FROM [catalog].[Packages] WHERE [Slug] = N'dinner-premium'), (SELECT [Id] FROM [catalog].[Items] WHERE [Name] = N'Chicken Roast'), 55.00, N'Chicken Roast', 20),
    ((SELECT [Id] FROM [catalog].[Packages] WHERE [Slug] = N'dinner-premium'), (SELECT [Id] FROM [catalog].[Items] WHERE [Name] = N'Beef Rezala'), 70.00, N'Beef Rezala', 30),
    ((SELECT [Id] FROM [catalog].[Packages] WHERE [Slug] = N'dinner-premium'), (SELECT [Id] FROM [catalog].[Items] WHERE [Name] = N'Hilsa / Rui Fish'), 35.00, N'Hilsa / Rui Fish', 40),
    ((SELECT [Id] FROM [catalog].[Packages] WHERE [Slug] = N'dinner-premium'), (SELECT [Id] FROM [catalog].[Items] WHERE [Name] = N'Dal'), 10.00, N'Dal', 50),
    ((SELECT [Id] FROM [catalog].[Packages] WHERE [Slug] = N'dinner-premium'), (SELECT [Id] FROM [catalog].[Items] WHERE [Name] = N'Vegetables'), 10.00, N'Vegetables', 60),
    ((SELECT [Id] FROM [catalog].[Packages] WHERE [Slug] = N'dinner-premium'), (SELECT [Id] FROM [catalog].[Items] WHERE [Name] = N'Salad'), 5.00, N'Salad', 70),
    ((SELECT [Id] FROM [catalog].[Packages] WHERE [Slug] = N'dinner-premium'), (SELECT [Id] FROM [catalog].[Items] WHERE [Name] = N'Borhani'), 15.00, N'Borhani', 80),
    ((SELECT [Id] FROM [catalog].[Packages] WHERE [Slug] = N'dinner-premium'), (SELECT [Id] FROM [catalog].[Items] WHERE [Name] = N'Firni'), 5.00, N'Firni', 90),
    ((SELECT [Id] FROM [catalog].[Packages] WHERE [Slug] = N'dinner-royal-dinner'), (SELECT [Id] FROM [catalog].[Items] WHERE [Name] = N'Morog Polao / Kacchi'), 75.00, N'Morog Polao / Kacchi', 10),
    ((SELECT [Id] FROM [catalog].[Packages] WHERE [Slug] = N'dinner-royal-dinner'), (SELECT [Id] FROM [catalog].[Items] WHERE [Name] = N'Beef Kala Bhuna'), 75.00, N'Beef Kala Bhuna', 20),
    ((SELECT [Id] FROM [catalog].[Packages] WHERE [Slug] = N'dinner-royal-dinner'), (SELECT [Id] FROM [catalog].[Items] WHERE [Name] = N'Mutton Rezala'), 85.00, N'Mutton Rezala', 30),
    ((SELECT [Id] FROM [catalog].[Packages] WHERE [Slug] = N'dinner-royal-dinner'), (SELECT [Id] FROM [catalog].[Items] WHERE [Name] = N'Fried Fish'), 35.00, N'Fried Fish', 40),
    ((SELECT [Id] FROM [catalog].[Packages] WHERE [Slug] = N'dinner-royal-dinner'), (SELECT [Id] FROM [catalog].[Items] WHERE [Name] = N'Dal'), 10.00, N'Dal', 50),
    ((SELECT [Id] FROM [catalog].[Packages] WHERE [Slug] = N'dinner-royal-dinner'), (SELECT [Id] FROM [catalog].[Items] WHERE [Name] = N'Borhani'), 15.00, N'Borhani', 60),
    ((SELECT [Id] FROM [catalog].[Packages] WHERE [Slug] = N'dinner-royal-dinner'), (SELECT [Id] FROM [catalog].[Items] WHERE [Name] = N'Salad'), 5.00, N'Salad', 70),
    ((SELECT [Id] FROM [catalog].[Packages] WHERE [Slug] = N'dinner-royal-dinner'), (SELECT [Id] FROM [catalog].[Items] WHERE [Name] = N'Shahi Tukra'), 15.00, N'Shahi Tukra', 80),
    ((SELECT [Id] FROM [catalog].[Packages] WHERE [Slug] = N'dinner-royal-dinner'), (SELECT [Id] FROM [catalog].[Items] WHERE [Name] = N'Fruit Platter'), 5.00, N'Fruit Platter', 90),
    ((SELECT [Id] FROM [catalog].[Packages] WHERE [Slug] = N'corporate-program-snacks-tea-break-package'), (SELECT [Id] FROM [catalog].[Items] WHERE [Name] = N'Samosa'), 10.00, N'Samosa', 10),
    ((SELECT [Id] FROM [catalog].[Packages] WHERE [Slug] = N'corporate-program-snacks-tea-break-package'), (SELECT [Id] FROM [catalog].[Items] WHERE [Name] = N'Singara'), 10.00, N'Singara', 20),
    ((SELECT [Id] FROM [catalog].[Packages] WHERE [Slug] = N'corporate-program-snacks-tea-break-package'), (SELECT [Id] FROM [catalog].[Items] WHERE [Name] = N'Chicken Pakora'), 15.00, N'Chicken Pakora', 30),
    ((SELECT [Id] FROM [catalog].[Packages] WHERE [Slug] = N'corporate-program-snacks-tea-break-package'), (SELECT [Id] FROM [catalog].[Items] WHERE [Name] = N'Biscuits'), 5.00, N'Biscuits', 40),
    ((SELECT [Id] FROM [catalog].[Packages] WHERE [Slug] = N'corporate-program-snacks-tea-break-package'), (SELECT [Id] FROM [catalog].[Items] WHERE [Name] = N'Tea / Coffee'), 3.00, N'Tea / Coffee', 50),
    ((SELECT [Id] FROM [catalog].[Packages] WHERE [Slug] = N'corporate-program-snacks-tea-break-package'), (SELECT [Id] FROM [catalog].[Items] WHERE [Name] = N'Water'), 2.00, N'Water', 60),
    ((SELECT [Id] FROM [catalog].[Packages] WHERE [Slug] = N'corporate-program-box-lunch'), (SELECT [Id] FROM [catalog].[Items] WHERE [Name] = N'Polao / Rice'), 20.00, N'Polao / Rice', 10),
    ((SELECT [Id] FROM [catalog].[Packages] WHERE [Slug] = N'corporate-program-box-lunch'), (SELECT [Id] FROM [catalog].[Items] WHERE [Name] = N'Chicken Curry'), 80.00, N'Chicken Curry', 20),
    ((SELECT [Id] FROM [catalog].[Packages] WHERE [Slug] = N'corporate-program-box-lunch'), (SELECT [Id] FROM [catalog].[Items] WHERE [Name] = N'Dal'), 10.00, N'Dal', 30),
    ((SELECT [Id] FROM [catalog].[Packages] WHERE [Slug] = N'corporate-program-box-lunch'), (SELECT [Id] FROM [catalog].[Items] WHERE [Name] = N'Vegetables'), 10.00, N'Vegetables', 40),
    ((SELECT [Id] FROM [catalog].[Packages] WHERE [Slug] = N'corporate-program-box-lunch'), (SELECT [Id] FROM [catalog].[Items] WHERE [Name] = N'Salad'), 5.00, N'Salad', 50),
    ((SELECT [Id] FROM [catalog].[Packages] WHERE [Slug] = N'corporate-program-box-lunch'), (SELECT [Id] FROM [catalog].[Items] WHERE [Name] = N'Mineral Water'), 5.00, N'Mineral Water', 60),
    ((SELECT [Id] FROM [catalog].[Packages] WHERE [Slug] = N'corporate-program-standard-buffet'), (SELECT [Id] FROM [catalog].[Items] WHERE [Name] = N'Rice & Polao'), 25.00, N'Rice & Polao', 10),
    ((SELECT [Id] FROM [catalog].[Packages] WHERE [Slug] = N'corporate-program-standard-buffet'), (SELECT [Id] FROM [catalog].[Items] WHERE [Name] = N'2 Chicken & Beef Dishes'), 110.00, N'2 Chicken & Beef Dishes', 20),
    ((SELECT [Id] FROM [catalog].[Packages] WHERE [Slug] = N'corporate-program-standard-buffet'), (SELECT [Id] FROM [catalog].[Items] WHERE [Name] = N'Fish'), 30.00, N'Fish', 30),
    ((SELECT [Id] FROM [catalog].[Packages] WHERE [Slug] = N'corporate-program-standard-buffet'), (SELECT [Id] FROM [catalog].[Items] WHERE [Name] = N'Dal'), 10.00, N'Dal', 40),
    ((SELECT [Id] FROM [catalog].[Packages] WHERE [Slug] = N'corporate-program-standard-buffet'), (SELECT [Id] FROM [catalog].[Items] WHERE [Name] = N'Vegetables'), 10.00, N'Vegetables', 50),
    ((SELECT [Id] FROM [catalog].[Packages] WHERE [Slug] = N'corporate-program-standard-buffet'), (SELECT [Id] FROM [catalog].[Items] WHERE [Name] = N'Salad Bar'), 10.00, N'Salad Bar', 60),
    ((SELECT [Id] FROM [catalog].[Packages] WHERE [Slug] = N'corporate-program-standard-buffet'), (SELECT [Id] FROM [catalog].[Items] WHERE [Name] = N'Dessert'), 15.00, N'Dessert', 70),
    ((SELECT [Id] FROM [catalog].[Packages] WHERE [Slug] = N'corporate-program-standard-buffet'), (SELECT [Id] FROM [catalog].[Items] WHERE [Name] = N'Soft Drink'), 10.00, N'Soft Drink', 80),
    ((SELECT [Id] FROM [catalog].[Packages] WHERE [Slug] = N'corporate-program-executive-buffet'), (SELECT [Id] FROM [catalog].[Items] WHERE [Name] = N'Kacchi / Biryani'), 90.00, N'Kacchi / Biryani', 10),
    ((SELECT [Id] FROM [catalog].[Packages] WHERE [Slug] = N'corporate-program-executive-buffet'), (SELECT [Id] FROM [catalog].[Items] WHERE [Name] = N'Roast'), 70.00, N'Roast', 20),
    ((SELECT [Id] FROM [catalog].[Packages] WHERE [Slug] = N'corporate-program-executive-buffet'), (SELECT [Id] FROM [catalog].[Items] WHERE [Name] = N'Kebab Station'), 60.00, N'Kebab Station', 30),
    ((SELECT [Id] FROM [catalog].[Packages] WHERE [Slug] = N'corporate-program-executive-buffet'), (SELECT [Id] FROM [catalog].[Items] WHERE [Name] = N'Fish'), 35.00, N'Fish', 40),
    ((SELECT [Id] FROM [catalog].[Packages] WHERE [Slug] = N'corporate-program-executive-buffet'), (SELECT [Id] FROM [catalog].[Items] WHERE [Name] = N'Salad Bar'), 15.00, N'Salad Bar', 50),
    ((SELECT [Id] FROM [catalog].[Packages] WHERE [Slug] = N'corporate-program-executive-buffet'), (SELECT [Id] FROM [catalog].[Items] WHERE [Name] = N'Soup'), 15.00, N'Soup', 60),
    ((SELECT [Id] FROM [catalog].[Packages] WHERE [Slug] = N'corporate-program-executive-buffet'), (SELECT [Id] FROM [catalog].[Items] WHERE [Name] = N'Dessert'), 15.00, N'Dessert', 70),
    ((SELECT [Id] FROM [catalog].[Packages] WHERE [Slug] = N'corporate-program-executive-buffet'), (SELECT [Id] FROM [catalog].[Items] WHERE [Name] = N'Beverages'), 15.00, N'Beverages', 80),
    ((SELECT [Id] FROM [catalog].[Packages] WHERE [Slug] = N'corporate-program-executive-buffet'), (SELECT [Id] FROM [catalog].[Items] WHERE [Name] = N'Tea/Coffee Corner'), 5.00, N'Tea/Coffee Corner', 90),
    ((SELECT [Id] FROM [catalog].[Packages] WHERE [Slug] = N'house-party-snacks-party'), (SELECT [Id] FROM [catalog].[Items] WHERE [Name] = N'Chicken Fry'), 35.00, N'Chicken Fry', 10),
    ((SELECT [Id] FROM [catalog].[Packages] WHERE [Slug] = N'house-party-snacks-party'), (SELECT [Id] FROM [catalog].[Items] WHERE [Name] = N'Shawarma / Roll'), 30.00, N'Shawarma / Roll', 20),
    ((SELECT [Id] FROM [catalog].[Packages] WHERE [Slug] = N'house-party-snacks-party'), (SELECT [Id] FROM [catalog].[Items] WHERE [Name] = N'Fuchka / Chotpoti'), 15.00, N'Fuchka / Chotpoti', 30),
    ((SELECT [Id] FROM [catalog].[Packages] WHERE [Slug] = N'house-party-snacks-party'), (SELECT [Id] FROM [catalog].[Items] WHERE [Name] = N'French Fries'), 15.00, N'French Fries', 40),
    ((SELECT [Id] FROM [catalog].[Packages] WHERE [Slug] = N'house-party-snacks-party'), (SELECT [Id] FROM [catalog].[Items] WHERE [Name] = N'Spring Roll'), 15.00, N'Spring Roll', 50),
    ((SELECT [Id] FROM [catalog].[Packages] WHERE [Slug] = N'house-party-snacks-party'), (SELECT [Id] FROM [catalog].[Items] WHERE [Name] = N'Soft Drink'), 5.00, N'Soft Drink', 60),
    ((SELECT [Id] FROM [catalog].[Packages] WHERE [Slug] = N'house-party-full-dinner-party'), (SELECT [Id] FROM [catalog].[Items] WHERE [Name] = N'Polao'), 30.00, N'Polao', 10),
    ((SELECT [Id] FROM [catalog].[Packages] WHERE [Slug] = N'house-party-full-dinner-party'), (SELECT [Id] FROM [catalog].[Items] WHERE [Name] = N'Chicken Roast'), 60.00, N'Chicken Roast', 20),
    ((SELECT [Id] FROM [catalog].[Packages] WHERE [Slug] = N'house-party-full-dinner-party'), (SELECT [Id] FROM [catalog].[Items] WHERE [Name] = N'Beef Bhuna'), 75.00, N'Beef Bhuna', 30),
    ((SELECT [Id] FROM [catalog].[Packages] WHERE [Slug] = N'house-party-full-dinner-party'), (SELECT [Id] FROM [catalog].[Items] WHERE [Name] = N'Fish Fry'), 40.00, N'Fish Fry', 40),
    ((SELECT [Id] FROM [catalog].[Packages] WHERE [Slug] = N'house-party-full-dinner-party'), (SELECT [Id] FROM [catalog].[Items] WHERE [Name] = N'Dal'), 10.00, N'Dal', 50),
    ((SELECT [Id] FROM [catalog].[Packages] WHERE [Slug] = N'house-party-full-dinner-party'), (SELECT [Id] FROM [catalog].[Items] WHERE [Name] = N'Vegetables'), 10.00, N'Vegetables', 60),
    ((SELECT [Id] FROM [catalog].[Packages] WHERE [Slug] = N'house-party-full-dinner-party'), (SELECT [Id] FROM [catalog].[Items] WHERE [Name] = N'Salad'), 5.00, N'Salad', 70),
    ((SELECT [Id] FROM [catalog].[Packages] WHERE [Slug] = N'house-party-full-dinner-party'), (SELECT [Id] FROM [catalog].[Items] WHERE [Name] = N'Borhani'), 10.00, N'Borhani', 80),
    ((SELECT [Id] FROM [catalog].[Packages] WHERE [Slug] = N'house-party-full-dinner-party'), (SELECT [Id] FROM [catalog].[Items] WHERE [Name] = N'Dessert'), 5.00, N'Dessert', 90),
    ((SELECT [Id] FROM [catalog].[Packages] WHERE [Slug] = N'house-party-bbq-night'), (SELECT [Id] FROM [catalog].[Items] WHERE [Name] = N'Chicken / Beef BBQ'), 180.00, N'Chicken / Beef BBQ', 10),
    ((SELECT [Id] FROM [catalog].[Packages] WHERE [Slug] = N'house-party-bbq-night'), (SELECT [Id] FROM [catalog].[Items] WHERE [Name] = N'Grilled Kebab'), 110.00, N'Grilled Kebab', 20),
    ((SELECT [Id] FROM [catalog].[Packages] WHERE [Slug] = N'house-party-bbq-night'), (SELECT [Id] FROM [catalog].[Items] WHERE [Name] = N'Naan'), 25.00, N'Naan', 30),
    ((SELECT [Id] FROM [catalog].[Packages] WHERE [Slug] = N'house-party-bbq-night'), (SELECT [Id] FROM [catalog].[Items] WHERE [Name] = N'Salad Bar'), 20.00, N'Salad Bar', 40),
    ((SELECT [Id] FROM [catalog].[Packages] WHERE [Slug] = N'house-party-bbq-night'), (SELECT [Id] FROM [catalog].[Items] WHERE [Name] = N'Dip Sauce'), 10.00, N'Dip Sauce', 50),
    ((SELECT [Id] FROM [catalog].[Packages] WHERE [Slug] = N'house-party-bbq-night'), (SELECT [Id] FROM [catalog].[Items] WHERE [Name] = N'Soft Drink'), 25.00, N'Soft Drink', 60),
    ((SELECT [Id] FROM [catalog].[Packages] WHERE [Slug] = N'house-party-bbq-night'), (SELECT [Id] FROM [catalog].[Items] WHERE [Name] = N'Dessert'), 10.00, N'Dessert', 70);
GO

-- PackageInclusions: full replace.
DELETE i FROM [catalog].[PackageInclusions] i
JOIN [catalog].[Packages] p ON p.[Id] = i.[PackageId] WHERE p.[Slug] IN (N'breakfast-classic-breakfast', N'breakfast-premium-breakfast', N'breakfast-royal-breakfast', N'lunch-standard', N'lunch-premium', N'lunch-royal-kacchi', N'dinner-standard', N'dinner-premium', N'dinner-royal-dinner', N'corporate-program-snacks-tea-break-package', N'corporate-program-box-lunch', N'corporate-program-standard-buffet', N'corporate-program-executive-buffet', N'house-party-snacks-party', N'house-party-full-dinner-party', N'house-party-bbq-night');
INSERT INTO [catalog].[PackageInclusions] ([PackageId], [Text], [SortOrder]) VALUES
    ((SELECT [Id] FROM [catalog].[Packages] WHERE [Slug] = N'corporate-program-executive-buffet'), N'Includes waiter service & cutlery', 10);
GO

-- PackageVariants: full replace.
DELETE v FROM [catalog].[PackageVariants] v
JOIN [catalog].[Packages] p ON p.[Id] = v.[PackageId] WHERE p.[Slug] IN (N'breakfast-classic-breakfast', N'breakfast-premium-breakfast', N'breakfast-royal-breakfast', N'lunch-standard', N'lunch-premium', N'lunch-royal-kacchi', N'dinner-standard', N'dinner-premium', N'dinner-royal-dinner', N'corporate-program-snacks-tea-break-package', N'corporate-program-box-lunch', N'corporate-program-standard-buffet', N'corporate-program-executive-buffet', N'house-party-snacks-party', N'house-party-full-dinner-party', N'house-party-bbq-night');
INSERT INTO [catalog].[PackageVariants] ([PackageId], [Name], [PriceDeltaPerHead], [CostDeltaPerHead], [IsDefault]) VALUES
    ((SELECT [Id] FROM [catalog].[Packages] WHERE [Slug] = N'lunch-royal-kacchi'), N'Chicken', 0.00, 0, 1),
    ((SELECT [Id] FROM [catalog].[Packages] WHERE [Slug] = N'lunch-royal-kacchi'), N'Mutton', 80.00, 0, 0);
GO

-- PackageAddOns: full replace.
DELETE pa FROM [catalog].[PackageAddOns] pa
JOIN [catalog].[Packages] p ON p.[Id] = pa.[PackageId] WHERE p.[Slug] IN (N'breakfast-classic-breakfast', N'breakfast-premium-breakfast', N'breakfast-royal-breakfast', N'lunch-standard', N'lunch-premium', N'lunch-royal-kacchi', N'dinner-standard', N'dinner-premium', N'dinner-royal-dinner', N'corporate-program-snacks-tea-break-package', N'corporate-program-box-lunch', N'corporate-program-standard-buffet', N'corporate-program-executive-buffet', N'house-party-snacks-party', N'house-party-full-dinner-party', N'house-party-bbq-night');
INSERT INTO [catalog].[PackageAddOns] ([PackageId], [AddOnId]) VALUES
    ((SELECT [Id] FROM [catalog].[Packages] WHERE [Slug] = N'house-party-bbq-night'), (SELECT [Id] FROM [catalog].[AddOns] WHERE [Name] = N'Outdoor Setup')),
    ((SELECT [Id] FROM [catalog].[Packages] WHERE [Slug] = N'house-party-bbq-night'), (SELECT [Id] FROM [catalog].[AddOns] WHERE [Name] = N'Live Chef Service'));
GO

