CREATE SCHEMA [identity] AUTHORIZATION [dbo];
GO
CREATE SCHEMA [nav] AUTHORIZATION [dbo];
GO
CREATE SCHEMA [catalog] AUTHORIZATION [dbo];
GO
CREATE SCHEMA [ordering] AUTHORIZATION [dbo];
GO
CREATE SCHEMA [customers] AUTHORIZATION [dbo];
GO
CREATE SCHEMA [engagement] AUTHORIZATION [dbo];
GO
CREATE SCHEMA [content] AUTHORIZATION [dbo];
GO
CREATE SCHEMA [reporting] AUTHORIZATION [dbo];
GO
