-- Post-deployment entrypoint. Idempotent: deploying twice changes nothing.
-- Catalogue seed is generated by ZRC.SeedImporter (Phase 2) — never hand-edit Catalogue.sql.

:r ./Seed/Roles.sql
:r ./Seed/Permissions.sql
:r ./Seed/RolePermissions.sql
:r ./Seed/MenuItems.sql
:r ./Seed/Catalogue.sql
