CREATE TABLE [content].[Entries]
(
 [Id] UNIQUEIDENTIFIER NOT NULL CONSTRAINT [DF_Entries_Id] DEFAULT NEWID(),
 [Kind] NVARCHAR(20) NOT NULL, [Key] NVARCHAR(100) NOT NULL,
 [Title] NVARCHAR(200) NOT NULL, [Body] NVARCHAR(4000) NOT NULL,
 [ImageUrl] NVARCHAR(1000) NULL, [SortOrder] INT NOT NULL CONSTRAINT [DF_Entries_Order] DEFAULT 0,
 [IsPublished] BIT NOT NULL CONSTRAINT [DF_Entries_Published] DEFAULT 0,
 [CreatedAt] DATETIME2(3) NOT NULL CONSTRAINT [DF_Entries_Created] DEFAULT SYSUTCDATETIME(),
 [CreatedBy] NVARCHAR(450) NULL, [UpdatedAt] DATETIME2(3) NULL, [UpdatedBy] NVARCHAR(450) NULL,
 [RowVersion] ROWVERSION NOT NULL,
 CONSTRAINT [PK_Entries] PRIMARY KEY ([Id]),
 CONSTRAINT [UX_Entries_Key] UNIQUE ([Kind],[Key]),
 CONSTRAINT [CK_Entries_Kind] CHECK ([Kind] IN (N'Page',N'Hero',N'Gallery',N'FAQ',N'Setting'))
);
