-- Generated by database/postgresql/generate.py; review before deployment.
CREATE SCHEMA IF NOT EXISTS "identity";
CREATE SCHEMA IF NOT EXISTS "nav";
CREATE SCHEMA IF NOT EXISTS "catalog";
CREATE SCHEMA IF NOT EXISTS "ordering";
CREATE SCHEMA IF NOT EXISTS "customers";
CREATE SCHEMA IF NOT EXISTS "engagement";
CREATE SCHEMA IF NOT EXISTS "content";
CREATE SCHEMA IF NOT EXISTS "reporting";
CREATE FUNCTION public.zrc_row_version() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN NEW."RowVersion" := decode(replace(gen_random_uuid()::text, '-', ''), 'hex'); RETURN NEW; END $$;
CREATE TABLE "catalog"."AddOns"
(
    "Id"            uuid NOT NULL DEFAULT (gen_random_uuid()),
    "Name"          varchar(256)    NOT NULL,
    "Description"   varchar(512)    NULL,
    "PricingType"   varchar(16)     NOT NULL,
    "Price"         DECIMAL(12, 2)   NOT NULL,
    "Cost"          DECIMAL(12, 2)   NOT NULL DEFAULT (0),
    "IsActive"      boolean              NOT NULL DEFAULT true,
    "CreatedAt"     timestamp without time zone     NOT NULL DEFAULT (timezone('UTC', now())),
    "CreatedBy"     varchar(128)    NULL,
    "UpdatedAt"     timestamp without time zone     NOT NULL DEFAULT (timezone('UTC', now())),
    "UpdatedBy"     varchar(128)    NULL,
    "RowVersion"    bytea DEFAULT decode(replace(gen_random_uuid()::text, '-', ''), 'hex')       NOT NULL,
    CONSTRAINT "PK_AddOns" PRIMARY KEY  ("Id"),
    CONSTRAINT "CK_AddOns_PricingType" CHECK ("PricingType" IN ('Flat', 'PerHead')),
    CONSTRAINT "CK_AddOns_Price_NonNegative" CHECK ("Price" >= 0),
    CONSTRAINT "CK_AddOns_Cost_NonNegative" CHECK ("Cost" >= 0)
);

CREATE TABLE "catalog"."Categories"
(
    "Id"            uuid NOT NULL DEFAULT (gen_random_uuid()),
    "Name"          varchar(128)    NOT NULL,
    "Slug"          varchar(128)    NOT NULL,
    "Description"   varchar(512)    NULL,
    "ImageUrl"      varchar(512)    NULL,
    "SortOrder"     INT              NOT NULL DEFAULT (0),
    "IsActive"      boolean              NOT NULL DEFAULT true,
    "IsDeleted"     boolean              NOT NULL DEFAULT false,
    "CreatedAt"     timestamp without time zone     NOT NULL DEFAULT (timezone('UTC', now())),
    "CreatedBy"     varchar(128)    NULL,
    "UpdatedAt"     timestamp without time zone     NOT NULL DEFAULT (timezone('UTC', now())),
    "UpdatedBy"     varchar(128)    NULL,
    "RowVersion"    bytea DEFAULT decode(replace(gen_random_uuid()::text, '-', ''), 'hex')       NOT NULL,
    CONSTRAINT "PK_Categories" PRIMARY KEY  ("Id")
);

CREATE TABLE "catalog"."Items"
(
    "Id"            uuid NOT NULL DEFAULT (gen_random_uuid()),
    "Name"          varchar(256)    NOT NULL,
    "NameBn"        varchar(256)    NULL,
    "Description"   varchar(512)    NULL,
    "IsVegetarian"  boolean              NOT NULL DEFAULT false,
    "Allergens"     varchar(256)    NULL,
    "ImageUrl"      varchar(512)    NULL,
    "IsActive"      boolean              NOT NULL DEFAULT true,
    "IsDeleted"     boolean              NOT NULL DEFAULT false,
    "CreatedAt"     timestamp without time zone     NOT NULL DEFAULT (timezone('UTC', now())),
    "CreatedBy"     varchar(128)    NULL,
    "UpdatedAt"     timestamp without time zone     NOT NULL DEFAULT (timezone('UTC', now())),
    "UpdatedBy"     varchar(128)    NULL,
    "RowVersion"    bytea DEFAULT decode(replace(gen_random_uuid()::text, '-', ''), 'hex')       NOT NULL,
    CONSTRAINT "PK_Items" PRIMARY KEY  ("Id")
);

CREATE TABLE "catalog"."PackageAddOns"
(
    "PackageId"     uuid NOT NULL,
    "AddOnId"       uuid NOT NULL,
    CONSTRAINT "PK_PackageAddOns" PRIMARY KEY  ("PackageId", "AddOnId")
);

CREATE TABLE "catalog"."PackageInclusions"
(
    "Id"            uuid NOT NULL DEFAULT (gen_random_uuid()),
    "PackageId"     uuid NOT NULL,
    "Text"          varchar(512)    NOT NULL,
    "SortOrder"     INT              NOT NULL DEFAULT (0),
    CONSTRAINT "PK_PackageInclusions" PRIMARY KEY  ("Id")
);

CREATE TABLE "catalog"."PackageItems"
(
    "PackageId"     uuid NOT NULL,
    "ItemId"        uuid NOT NULL,
    "CostPerHead"   DECIMAL(12, 2)   NOT NULL,
    "DisplayName"   varchar(256)    NULL,
    "SortOrder"     INT              NOT NULL DEFAULT (0),
    CONSTRAINT "PK_PackageItems" PRIMARY KEY  ("PackageId", "ItemId"),
    CONSTRAINT "CK_PackageItems_Cost_NonNegative" CHECK ("CostPerHead" >= 0)
);

CREATE TABLE "catalog"."Packages"
(
    "Id"                uuid NOT NULL DEFAULT (gen_random_uuid()),
    "CategoryId"        uuid NOT NULL,
    "Name"              varchar(256)    NOT NULL,
    "Slug"              varchar(256)    NOT NULL,
    "Tagline"           varchar(512)    NULL,
    "Description"       varchar(1024)   NULL,
    "SalePricePerHead"  DECIMAL(12, 2)   NOT NULL,
    "MinGuests"         INT              NOT NULL DEFAULT (1),
    "MaxGuests"         INT              NULL,
    "HeroImageUrl"      varchar(512)    NULL,
    "Model3DUrl"        varchar(512)    NULL,
    "SortOrder"         INT              NOT NULL DEFAULT (0),
    "IsFeatured"        boolean              NOT NULL DEFAULT false,
    "IsActive"          boolean              NOT NULL DEFAULT true,
    "IsDeleted"         boolean              NOT NULL DEFAULT false,
    "CreatedAt"         timestamp without time zone     NOT NULL DEFAULT (timezone('UTC', now())),
    "CreatedBy"         varchar(128)    NULL,
    "UpdatedAt"         timestamp without time zone     NOT NULL DEFAULT (timezone('UTC', now())),
    "UpdatedBy"         varchar(128)    NULL,
    "RowVersion"        bytea DEFAULT decode(replace(gen_random_uuid()::text, '-', ''), 'hex')       NOT NULL,
    CONSTRAINT "PK_Packages" PRIMARY KEY  ("Id"),
    CONSTRAINT "CK_Packages_SalePrice_Positive" CHECK ("SalePricePerHead" > 0),
    CONSTRAINT "CK_Packages_Guests" CHECK ("MinGuests" >= 1 AND ("MaxGuests" IS NULL OR "MaxGuests" >= "MinGuests"))
);

CREATE TABLE "catalog"."PackageVariants"
(
    "Id"                uuid NOT NULL DEFAULT (gen_random_uuid()),
    "PackageId"         uuid NOT NULL,
    "Name"              varchar(128)    NOT NULL,
    "PriceDeltaPerHead" DECIMAL(12, 2)   NOT NULL DEFAULT (0),
    "CostDeltaPerHead"  DECIMAL(12, 2)   NOT NULL DEFAULT (0),
    "IsDefault"         boolean              NOT NULL DEFAULT false,
    CONSTRAINT "PK_PackageVariants" PRIMARY KEY  ("Id")
);

CREATE TABLE "catalog"."PriceHistory"
(
    "Id"            BIGINT           GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "PackageId"     uuid NOT NULL,
    "OldPrice"      DECIMAL(12, 2)   NOT NULL,
    "NewPrice"      DECIMAL(12, 2)   NOT NULL,
    "ChangedAt"     timestamp without time zone     NOT NULL DEFAULT (timezone('UTC', now())),
    "ChangedBy"     varchar(128)    NULL,
    CONSTRAINT "PK_PriceHistory" PRIMARY KEY  ("Id"),
    CONSTRAINT "CK_PriceHistory_Prices_Positive" CHECK ("OldPrice" > 0 AND "NewPrice" > 0)
);

CREATE TABLE "content"."Entries"
(
 "Id" uuid NOT NULL DEFAULT gen_random_uuid(),
 "Kind" varchar(20) NOT NULL, "Key" varchar(100) NOT NULL,
 "Title" varchar(200) NOT NULL, "Body" varchar(4000) NOT NULL,
 "ImageUrl" varchar(1000) NULL, "SortOrder" INT NOT NULL DEFAULT 0,
 "IsPublished" boolean NOT NULL DEFAULT false,
 "CreatedAt" timestamp without time zone NOT NULL DEFAULT timezone('UTC', now()),
 "CreatedBy" varchar(450) NULL, "UpdatedAt" timestamp without time zone NULL, "UpdatedBy" varchar(450) NULL,
 "RowVersion" bytea DEFAULT decode(replace(gen_random_uuid()::text, '-', ''), 'hex') NOT NULL,
 CONSTRAINT "PK_Entries" PRIMARY KEY ("Id"),
 CONSTRAINT "UX_Entries_Key" UNIQUE ("Kind","Key"),
 CONSTRAINT "CK_Entries_Kind" CHECK ("Kind" IN ('Page','Hero','Gallery','FAQ','Setting'))
);

CREATE TABLE "customers"."Customers"
(
 "Id" uuid NOT NULL DEFAULT gen_random_uuid(),
 "Name" varchar(160) NOT NULL,
 "Phone" varchar(20) NOT NULL,
 "Email" varchar(254) NULL,
 "Address" varchar(1000) NULL,
 "Notes" varchar(2000) NULL,
 "IsDeleted" boolean NOT NULL DEFAULT false,
 "CreatedAt" timestamp without time zone NOT NULL DEFAULT timezone('UTC', now()),
 "CreatedBy" varchar(450) NULL,
 "UpdatedAt" timestamp without time zone NULL, "UpdatedBy" varchar(450) NULL,
 "RowVersion" bytea DEFAULT decode(replace(gen_random_uuid()::text, '-', ''), 'hex') NOT NULL,
 CONSTRAINT "PK_Customers" PRIMARY KEY ("Id"),
 CONSTRAINT "CK_Customers_Name" CHECK (length(LTRIM(RTRIM("Name"))) > 0)
);

CREATE TABLE "engagement"."Requests"
(
 "Id" uuid NOT NULL DEFAULT gen_random_uuid(),
 "Kind" varchar(20) NOT NULL, "Name" varchar(160) NOT NULL,
 "Email" varchar(254) NULL, "Phone" varchar(20) NULL,
 "Subject" varchar(160) NULL, "Message" varchar(4000) NOT NULL,
 "Status" varchar(20) NOT NULL DEFAULT 'New',
 "StaffNotes" varchar(2000) NULL,
 "CreatedAt" timestamp without time zone NOT NULL DEFAULT timezone('UTC', now()),
 "CreatedBy" varchar(450) NULL, "UpdatedAt" timestamp without time zone NULL, "UpdatedBy" varchar(450) NULL,
 "RowVersion" bytea DEFAULT decode(replace(gen_random_uuid()::text, '-', ''), 'hex') NOT NULL,
 CONSTRAINT "PK_Requests" PRIMARY KEY ("Id"),
 CONSTRAINT "CK_Requests_Kind" CHECK ("Kind" IN ('Inquiry','Contact','Newsletter')),
 CONSTRAINT "CK_Requests_Status" CHECK ("Status" IN ('New','InProgress','Closed'))
);

CREATE TABLE "engagement"."Reviews"
(
 "Id" uuid NOT NULL DEFAULT gen_random_uuid(),
 "AuthorName" varchar(160) NOT NULL, "Rating" INT NOT NULL,
 "Body" varchar(2000) NOT NULL, "EventType" varchar(160) NULL,
 "Status" varchar(20) NOT NULL DEFAULT 'Pending',
 "IsFeatured" boolean NOT NULL DEFAULT false,
 "CreatedAt" timestamp without time zone NOT NULL DEFAULT timezone('UTC', now()),
 "CreatedBy" varchar(450) NULL, "UpdatedAt" timestamp without time zone NULL, "UpdatedBy" varchar(450) NULL,
 "RowVersion" bytea DEFAULT decode(replace(gen_random_uuid()::text, '-', ''), 'hex') NOT NULL,
 CONSTRAINT "PK_Reviews" PRIMARY KEY ("Id"),
 CONSTRAINT "CK_Reviews_Rating" CHECK ("Rating" BETWEEN 1 AND 5),
 CONSTRAINT "CK_Reviews_Status" CHECK ("Status" IN ('Pending','Approved','Rejected')),
 CONSTRAINT "CK_Reviews_Feature" CHECK ("IsFeatured"=false OR "Status"='Approved')
);

CREATE TABLE "identity"."RefreshTokens"
(
    "Id"                 uuid NOT NULL DEFAULT (gen_random_uuid()),
    "UserId"             varchar(450)    NOT NULL,
    "TokenHash"          varchar(256)    NOT NULL,
    "ExpiresAt"          timestamp without time zone     NOT NULL,
    "CreatedAt"          timestamp without time zone     NOT NULL DEFAULT (timezone('UTC', now())),
    "CreatedByIp"        varchar(64)     NULL,
    "RevokedAt"          timestamp without time zone     NULL,
    "RevokedByIp"        varchar(64)     NULL,
    "ReplacedByTokenHash" varchar(256)   NULL,
    CONSTRAINT "PK_RefreshTokens" PRIMARY KEY  ("Id"),
    CONSTRAINT "CK_RefreshTokens_Expiry" CHECK ("ExpiresAt" > "CreatedAt")
);

CREATE TABLE "identity"."AuditLogs"
(
    "Id"         BIGINT         GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "OccurredAt" timestamp without time zone   NOT NULL DEFAULT (timezone('UTC', now())),
    "UserId"     varchar(450)  NULL,
    "Action"     varchar(128)  NOT NULL,
    "EntityType" varchar(256)  NULL,
    "EntityId"   varchar(128)  NULL,
    "BeforeJson" text  NULL,
    "AfterJson"  text  NULL,
    "IpAddress"  varchar(64)   NULL,
    CONSTRAINT "PK_AuditLogs" PRIMARY KEY  ("Id")
);

CREATE TABLE "identity"."OutboxMessages"
(
    "Id"          uuid NOT NULL DEFAULT (gen_random_uuid()),
    "EventType"   varchar(512)    NOT NULL,
    "Payload"     text    NOT NULL,
    "OccurredAt"  timestamp without time zone     NOT NULL DEFAULT (timezone('UTC', now())),
    "ProcessedAt" timestamp without time zone     NULL,
    "Error"       text    NULL,
    "CreatedAt"   timestamp without time zone     NOT NULL DEFAULT (timezone('UTC', now())),
    CONSTRAINT "PK_OutboxMessages" PRIMARY KEY  ("Id")
);

CREATE TABLE "identity"."UserClaims"
(
    "Id"         INT            GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "UserId"     varchar(450)  NOT NULL,
    "ClaimType"  text  NULL,
    "ClaimValue" text  NULL,
    CONSTRAINT "PK_UserClaims" PRIMARY KEY  ("Id")
);

CREATE TABLE "identity"."UserLogins"
(
    "LoginProvider"       varchar(128) NOT NULL,
    "ProviderKey"         varchar(450) NOT NULL,
    "ProviderDisplayName" text NULL,
    "UserId"              varchar(450) NOT NULL,
    CONSTRAINT "PK_UserLogins" PRIMARY KEY  ("LoginProvider", "ProviderKey")
);

CREATE TABLE "identity"."UserTokens"
(
    "UserId"        varchar(450) NOT NULL,
    "LoginProvider" varchar(128) NOT NULL,
    "Name"          varchar(128) NOT NULL,
    "Value"         text NULL,
    CONSTRAINT "PK_UserTokens" PRIMARY KEY  ("UserId", "LoginProvider", "Name")
);

CREATE TABLE "identity"."RoleClaims"
(
    "Id"         INT           GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "RoleId"     varchar(450) NOT NULL,
    "ClaimType"  text NULL,
    "ClaimValue" text NULL,
    CONSTRAINT "PK_RoleClaims" PRIMARY KEY  ("Id")
);

CREATE TABLE "identity"."Permissions"
(
    "Id"          INT            GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "Code"        varchar(128)  NOT NULL,
    "Module"      varchar(64)   NOT NULL,
    "Description" varchar(512)  NULL,
    "CreatedAt"   timestamp without time zone   NOT NULL DEFAULT (timezone('UTC', now())),
    CONSTRAINT "PK_Permissions" PRIMARY KEY  ("Id")
);

CREATE TABLE "identity"."RolePermissions"
(
    "RoleId"       varchar(450) NOT NULL,
    "PermissionId" INT           NOT NULL,
    "GrantedAt"    timestamp without time zone  NOT NULL DEFAULT (timezone('UTC', now())),
    "GrantedBy"    varchar(128) NULL,
    CONSTRAINT "PK_RolePermissions" PRIMARY KEY  ("RoleId", "PermissionId")
);

CREATE TABLE "identity"."UserRoles"
(
    "UserId"     varchar(450) NOT NULL,
    "RoleId"     varchar(450) NOT NULL,
    "AssignedAt" timestamp without time zone  NOT NULL DEFAULT (timezone('UTC', now())),
    "AssignedBy" varchar(128) NULL,
    CONSTRAINT "PK_UserRoles" PRIMARY KEY  ("UserId", "RoleId")
);

CREATE TABLE "identity"."Roles"
(
    "Id"               varchar(450) NOT NULL,
    "Name"             varchar(128) NOT NULL,
    "NormalizedName"   varchar(128) NULL,
    "ConcurrencyStamp" text  NULL,
    "Description"      varchar(512) NULL,
    "IsSystem"         boolean           NOT NULL DEFAULT false,
    "CreatedAt"        timestamp without time zone  NOT NULL DEFAULT (timezone('UTC', now())),
    "CreatedBy"        varchar(128) NULL,
    "UpdatedAt"        timestamp without time zone  NOT NULL DEFAULT (timezone('UTC', now())),
    "UpdatedBy"        varchar(128) NULL,
    "RowVersion"       bytea DEFAULT decode(replace(gen_random_uuid()::text, '-', ''), 'hex')    NOT NULL,
    CONSTRAINT "PK_Roles" PRIMARY KEY  ("Id")
);

CREATE TABLE "identity"."Users"
(
    "Id"                   varchar(450)  NOT NULL,
    "UserName"             varchar(256)  NULL,
    "NormalizedUserName"   varchar(256)  NULL,
    "Email"                varchar(256)  NULL,
    "NormalizedEmail"      varchar(256)  NULL,
    "EmailConfirmed"       boolean            NOT NULL DEFAULT false,
    "PasswordHash"         text  NULL,
    "SecurityStamp"        text  NULL,
    "ConcurrencyStamp"     text  NULL,
    "PhoneNumber"          varchar(32)   NULL,
    "PhoneNumberConfirmed" boolean            NOT NULL DEFAULT false,
    "TwoFactorEnabled"     boolean            NOT NULL DEFAULT false,
    "LockoutEnd"           timestamp with time zone NULL,
    "LockoutEnabled"       boolean            NOT NULL DEFAULT true,
    "AccessFailedCount"    INT            NOT NULL DEFAULT (0),
    "DisplayName"          varchar(128)  NULL,
    "IsStaff"              boolean            NOT NULL DEFAULT false,
    "IsActive"             boolean            NOT NULL DEFAULT true,
    "CreatedAt"            timestamp without time zone   NOT NULL DEFAULT (timezone('UTC', now())),
    "CreatedBy"            varchar(128)  NULL,
    "UpdatedAt"            timestamp without time zone   NOT NULL DEFAULT (timezone('UTC', now())),
    "UpdatedBy"            varchar(128)  NULL,
    "RowVersion"           bytea DEFAULT decode(replace(gen_random_uuid()::text, '-', ''), 'hex')     NOT NULL,
    CONSTRAINT "PK_Users" PRIMARY KEY  ("Id")
);

CREATE TABLE "nav"."MenuItems"
(
    "Id"                  uuid NOT NULL DEFAULT (gen_random_uuid()),
    "ParentId"            uuid NULL,
    "Key"                 varchar(128)    NOT NULL,
    "Label"               varchar(128)    NOT NULL,
    "LabelBn"             varchar(128)    NULL,
    "Icon"                varchar(128)    NULL,
    "Route"               varchar(256)    NULL,
    "ExternalUrl"         varchar(512)    NULL,
    "RequiredPermission"  varchar(128)    NULL,
    "MenuArea"            varchar(16)     NOT NULL DEFAULT ('Admin'),
    "SortOrder"           INT              NOT NULL DEFAULT (0),
    "IsVisible"           boolean              NOT NULL DEFAULT true,
    "IsDeleted"           boolean              NOT NULL DEFAULT false,
    "CreatedAt"           timestamp without time zone     NOT NULL DEFAULT (timezone('UTC', now())),
    "CreatedBy"           varchar(128)    NULL,
    "UpdatedAt"           timestamp without time zone     NOT NULL DEFAULT (timezone('UTC', now())),
    "UpdatedBy"           varchar(128)    NULL,
    "RowVersion"          bytea DEFAULT decode(replace(gen_random_uuid()::text, '-', ''), 'hex')       NOT NULL,
    CONSTRAINT "PK_MenuItems" PRIMARY KEY  ("Id"),
    CONSTRAINT "CK_MenuItems_Area" CHECK ("MenuArea" IN ('Admin', 'Public')),
    CONSTRAINT "CK_MenuItems_Target" CHECK ("Route" IS NOT NULL OR "ExternalUrl" IS NOT NULL OR "ParentId" IS NULL)
);

CREATE TABLE "ordering"."Orders"
(
 "Id" uuid NOT NULL DEFAULT gen_random_uuid(),
 "OrderNo" varchar(40) NOT NULL,
 "CustomerId" uuid NULL,
 "UserId" varchar(450) NULL,
 "ContactName" varchar(160) NOT NULL, "ContactPhone" varchar(20) NOT NULL,
 "PackageId" uuid NOT NULL, "PackageName" varchar(160) NOT NULL,
 "CategoryName" varchar(160) NOT NULL, "VariantName" varchar(160) NULL,
 "Guests" INT NOT NULL, "EventDate" DATE NOT NULL, "EventTime" TIME(0) NOT NULL,
 "EventType" varchar(160) NOT NULL, "VenueAddress" varchar(1000) NOT NULL,
 "SpecialInstructions" varchar(2000) NULL,
 "Status" varchar(24) NOT NULL DEFAULT 'Pending',
 "UnitPricePerHead" DECIMAL(12,2) NOT NULL, "UnitCostPerHead" DECIMAL(12,2) NOT NULL,
 "SubTotal" DECIMAL(12,2) NOT NULL, "AddOnTotal" DECIMAL(12,2) NOT NULL,
 "DeliveryCharge" DECIMAL(12,2) NOT NULL, "Discount" DECIMAL(12,2) NOT NULL,
 "GrandTotal" DECIMAL(12,2) NOT NULL, "TotalCost" DECIMAL(12,2) NOT NULL,
 "SnapshotJson" text NOT NULL,
 "CreatedAt" timestamp without time zone NOT NULL DEFAULT timezone('UTC', now()),
 "CreatedBy" varchar(450) NULL, "UpdatedAt" timestamp without time zone NULL, "UpdatedBy" varchar(450) NULL,
 "RowVersion" bytea DEFAULT decode(replace(gen_random_uuid()::text, '-', ''), 'hex') NOT NULL,
 CONSTRAINT "PK_Orders" PRIMARY KEY ("Id"),
 CONSTRAINT "CK_Orders_Guests" CHECK ("Guests" BETWEEN 1 AND 100000),
 CONSTRAINT "CK_Orders_Status" CHECK ("Status" IN ('Pending','Confirmed','InPreparation','Dispatched','Delivered','Completed','Cancelled','Rejected')),
 CONSTRAINT "CK_Orders_Money" CHECK ("UnitPricePerHead">0 AND "UnitCostPerHead">=0 AND "SubTotal">0 AND "AddOnTotal">=0 AND "DeliveryCharge">=0 AND "Discount">=0 AND "GrandTotal">0 AND "TotalCost">=0 AND "GrandTotal"="SubTotal"+"AddOnTotal"+"DeliveryCharge"-"Discount"),
 CONSTRAINT "CK_Orders_Snapshot" CHECK (("SnapshotJson"::jsonb IS NOT NULL))
);

CREATE TABLE "ordering"."OrderStatusHistory"
(
 "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, "OrderId" uuid NOT NULL,
 "FromStatus" varchar(24) NULL, "ToStatus" varchar(24) NOT NULL, "Note" varchar(1000) NULL,
 "ChangedAt" timestamp without time zone NOT NULL DEFAULT timezone('UTC', now()),
 "ChangedBy" varchar(450) NULL,
 CONSTRAINT "PK_OrderStatusHistory" PRIMARY KEY ("Id")
);

CREATE TABLE "ordering"."Payments"
(
 "Id" uuid NOT NULL DEFAULT gen_random_uuid(),
 "OrderId" uuid NOT NULL, "Method" varchar(20) NOT NULL,
 "Amount" DECIMAL(12,2) NOT NULL, "Reference" varchar(120) NULL,
 "PaidAt" timestamp without time zone NOT NULL DEFAULT timezone('UTC', now()),
 "RecordedBy" varchar(450) NULL,
 CONSTRAINT "PK_Payments" PRIMARY KEY ("Id"),
 CONSTRAINT "CK_Payments_Amount" CHECK ("Amount">0),
 CONSTRAINT "CK_Payments_Method" CHECK ("Method" IN ('Cash','bKash','Nagad','Bank','Card'))
);

ALTER TABLE "catalog"."PackageAddOns" ADD CONSTRAINT "FK_PackageAddOns_Packages" FOREIGN KEY ("PackageId") REFERENCES "catalog"."Packages" ("Id");

ALTER TABLE "catalog"."PackageAddOns" ADD CONSTRAINT "FK_PackageAddOns_AddOns" FOREIGN KEY ("AddOnId") REFERENCES "catalog"."AddOns" ("Id");

ALTER TABLE "catalog"."PackageInclusions" ADD CONSTRAINT "FK_PackageInclusions_Packages" FOREIGN KEY ("PackageId") REFERENCES "catalog"."Packages" ("Id");

ALTER TABLE "catalog"."PackageItems" ADD CONSTRAINT "FK_PackageItems_Packages" FOREIGN KEY ("PackageId") REFERENCES "catalog"."Packages" ("Id");

ALTER TABLE "catalog"."PackageItems" ADD CONSTRAINT "FK_PackageItems_Items" FOREIGN KEY ("ItemId") REFERENCES "catalog"."Items" ("Id");

ALTER TABLE "catalog"."Packages" ADD CONSTRAINT "FK_Packages_Categories" FOREIGN KEY ("CategoryId") REFERENCES "catalog"."Categories" ("Id");

ALTER TABLE "catalog"."PackageVariants" ADD CONSTRAINT "FK_PackageVariants_Packages" FOREIGN KEY ("PackageId") REFERENCES "catalog"."Packages" ("Id");

ALTER TABLE "catalog"."PriceHistory" ADD CONSTRAINT "FK_PriceHistory_Packages" FOREIGN KEY ("PackageId") REFERENCES "catalog"."Packages" ("Id");

ALTER TABLE "identity"."RefreshTokens" ADD CONSTRAINT "FK_RefreshTokens_Users" FOREIGN KEY ("UserId") REFERENCES "identity"."Users" ("Id") ON DELETE CASCADE;

ALTER TABLE "identity"."UserClaims" ADD CONSTRAINT "FK_UserClaims_Users" FOREIGN KEY ("UserId") REFERENCES "identity"."Users" ("Id") ON DELETE CASCADE;

ALTER TABLE "identity"."UserLogins" ADD CONSTRAINT "FK_UserLogins_Users" FOREIGN KEY ("UserId") REFERENCES "identity"."Users" ("Id") ON DELETE CASCADE;

ALTER TABLE "identity"."UserTokens" ADD CONSTRAINT "FK_UserTokens_Users" FOREIGN KEY ("UserId") REFERENCES "identity"."Users" ("Id") ON DELETE CASCADE;

ALTER TABLE "identity"."RoleClaims" ADD CONSTRAINT "FK_RoleClaims_Roles" FOREIGN KEY ("RoleId") REFERENCES "identity"."Roles" ("Id") ON DELETE CASCADE;

ALTER TABLE "identity"."RolePermissions" ADD CONSTRAINT "FK_RolePermissions_Roles" FOREIGN KEY ("RoleId") REFERENCES "identity"."Roles" ("Id") ON DELETE CASCADE;

ALTER TABLE "identity"."RolePermissions" ADD CONSTRAINT "FK_RolePermissions_Permissions" FOREIGN KEY ("PermissionId") REFERENCES "identity"."Permissions" ("Id") ON DELETE CASCADE;

ALTER TABLE "identity"."UserRoles" ADD CONSTRAINT "FK_UserRoles_Users" FOREIGN KEY ("UserId") REFERENCES "identity"."Users" ("Id") ON DELETE CASCADE;

ALTER TABLE "identity"."UserRoles" ADD CONSTRAINT "FK_UserRoles_Roles" FOREIGN KEY ("RoleId") REFERENCES "identity"."Roles" ("Id") ON DELETE CASCADE;

ALTER TABLE "nav"."MenuItems" ADD CONSTRAINT "FK_MenuItems_Parent" FOREIGN KEY ("ParentId") REFERENCES "nav"."MenuItems" ("Id");

ALTER TABLE "ordering"."Orders" ADD CONSTRAINT "FK_Orders_Customers" FOREIGN KEY ("CustomerId") REFERENCES "customers"."Customers"("Id");

ALTER TABLE "ordering"."OrderStatusHistory" ADD CONSTRAINT "FK_OrderStatusHistory_Order" FOREIGN KEY ("OrderId") REFERENCES "ordering"."Orders"("Id");

ALTER TABLE "ordering"."Payments" ADD CONSTRAINT "FK_Payments_Order" FOREIGN KEY ("OrderId") REFERENCES "ordering"."Orders"("Id");

CREATE UNIQUE INDEX "UX_AddOns_Name" ON "catalog"."AddOns" ("Name");

CREATE UNIQUE INDEX "UX_Categories_Slug" ON "catalog"."Categories" ("Slug") WHERE "IsDeleted" = false;

CREATE UNIQUE INDEX "UX_Categories_Name" ON "catalog"."Categories" ("Name") WHERE "IsDeleted" = false;

CREATE UNIQUE INDEX "UX_Items_Name" ON "catalog"."Items" ("Name") WHERE "IsDeleted" = false;

CREATE INDEX "IX_PackageInclusions_Package" ON "catalog"."PackageInclusions" ("PackageId");

CREATE INDEX "IX_PackageItems_Item" ON "catalog"."PackageItems" ("ItemId");

CREATE UNIQUE INDEX "UX_Packages_Slug" ON "catalog"."Packages" ("Slug") WHERE "IsDeleted" = false;

CREATE INDEX "IX_Packages_Category" ON "catalog"."Packages" ("CategoryId") WHERE "IsDeleted" = false;

CREATE INDEX "IX_PackageVariants_Package" ON "catalog"."PackageVariants" ("PackageId");

CREATE INDEX "IX_PriceHistory_Package" ON "catalog"."PriceHistory" ("PackageId");

CREATE UNIQUE INDEX "UX_Customers_Phone" ON "customers"."Customers" ("Phone") WHERE "IsDeleted" = false;

CREATE UNIQUE INDEX "UX_RefreshTokens_TokenHash" ON "identity"."RefreshTokens" ("TokenHash");

CREATE INDEX "IX_RefreshTokens_UserId" ON "identity"."RefreshTokens" ("UserId", "ExpiresAt");

CREATE INDEX "IX_AuditLogs_OccurredAt" ON "identity"."AuditLogs" ("OccurredAt" DESC);

CREATE INDEX "IX_AuditLogs_Entity" ON "identity"."AuditLogs" ("EntityType", "EntityId");

CREATE INDEX "IX_Outbox_Unprocessed" ON "identity"."OutboxMessages" ("OccurredAt") WHERE "ProcessedAt" IS NULL;

CREATE INDEX "IX_UserClaims_UserId" ON "identity"."UserClaims" ("UserId");

CREATE INDEX "IX_UserLogins_UserId" ON "identity"."UserLogins" ("UserId");

CREATE INDEX "IX_RoleClaims_RoleId" ON "identity"."RoleClaims" ("RoleId");

CREATE UNIQUE INDEX "UX_Permissions_Code" ON "identity"."Permissions" ("Code");

CREATE INDEX "IX_Permissions_Module" ON "identity"."Permissions" ("Module");

CREATE UNIQUE INDEX "IX_Roles_NormalizedName" ON "identity"."Roles" ("NormalizedName") WHERE "NormalizedName" IS NOT NULL;

CREATE UNIQUE INDEX "UX_Roles_Name" ON "identity"."Roles" ("Name");

CREATE UNIQUE INDEX "IX_Users_NormalizedUserName" ON "identity"."Users" ("NormalizedUserName") WHERE "NormalizedUserName" IS NOT NULL;

CREATE UNIQUE INDEX "IX_Users_NormalizedEmail" ON "identity"."Users" ("NormalizedEmail") WHERE "NormalizedEmail" IS NOT NULL;

CREATE UNIQUE INDEX "UX_MenuItems_Key_Area" ON "nav"."MenuItems" ("Key", "MenuArea") WHERE "IsDeleted" = false;

CREATE INDEX "IX_MenuItems_Parent_Sort" ON "nav"."MenuItems" ("ParentId", "SortOrder") WHERE "IsDeleted" = false;

CREATE UNIQUE INDEX "UX_Orders_Number" ON "ordering"."Orders"("OrderNo");

CREATE INDEX "IX_Orders_EventDate" ON "ordering"."Orders"("EventDate","Status");

CREATE INDEX "IX_Orders_Customer" ON "ordering"."Orders"("CustomerId");

CREATE TRIGGER row_version BEFORE INSERT OR UPDATE ON "catalog"."AddOns" FOR EACH ROW EXECUTE FUNCTION public.zrc_row_version();

CREATE TRIGGER row_version BEFORE INSERT OR UPDATE ON "catalog"."Categories" FOR EACH ROW EXECUTE FUNCTION public.zrc_row_version();

CREATE TRIGGER row_version BEFORE INSERT OR UPDATE ON "catalog"."Items" FOR EACH ROW EXECUTE FUNCTION public.zrc_row_version();

CREATE TRIGGER row_version BEFORE INSERT OR UPDATE ON "catalog"."Packages" FOR EACH ROW EXECUTE FUNCTION public.zrc_row_version();

CREATE TRIGGER row_version BEFORE INSERT OR UPDATE ON "content"."Entries" FOR EACH ROW EXECUTE FUNCTION public.zrc_row_version();

CREATE TRIGGER row_version BEFORE INSERT OR UPDATE ON "customers"."Customers" FOR EACH ROW EXECUTE FUNCTION public.zrc_row_version();

CREATE TRIGGER row_version BEFORE INSERT OR UPDATE ON "engagement"."Requests" FOR EACH ROW EXECUTE FUNCTION public.zrc_row_version();

CREATE TRIGGER row_version BEFORE INSERT OR UPDATE ON "engagement"."Reviews" FOR EACH ROW EXECUTE FUNCTION public.zrc_row_version();

CREATE TRIGGER row_version BEFORE INSERT OR UPDATE ON "identity"."Roles" FOR EACH ROW EXECUTE FUNCTION public.zrc_row_version();

CREATE TRIGGER row_version BEFORE INSERT OR UPDATE ON "identity"."Users" FOR EACH ROW EXECUTE FUNCTION public.zrc_row_version();

CREATE TRIGGER row_version BEFORE INSERT OR UPDATE ON "nav"."MenuItems" FOR EACH ROW EXECUTE FUNCTION public.zrc_row_version();

CREATE TRIGGER row_version BEFORE INSERT OR UPDATE ON "ordering"."Orders" FOR EACH ROW EXECUTE FUNCTION public.zrc_row_version();

CREATE VIEW "catalog"."vw_PackageCosting"
AS
SELECT
    p."Id" AS "PackageId",
    p."Name" AS "PackageName",
    p."Slug" AS "PackageSlug",
    c."Name" AS "CategoryName",
    p."SalePricePerHead" AS "SalePricePerHead",
    COALESCE((
        SELECT SUM(pi."CostPerHead")
        FROM "catalog"."PackageItems" pi
        WHERE pi."PackageId" = p."Id"
    ), 0) AS "TotalCost",
    p."SalePricePerHead" - COALESCE((
        SELECT SUM(pi."CostPerHead")
        FROM "catalog"."PackageItems" pi
        WHERE pi."PackageId" = p."Id"
    ), 0) AS "Profit",
    CASE
        WHEN p."SalePricePerHead" = 0 THEN 0
        ELSE (p."SalePricePerHead" - COALESCE((
            SELECT SUM(pi."CostPerHead")
            FROM "catalog"."PackageItems" pi
            WHERE pi."PackageId" = p."Id"
        ), 0)) / p."SalePricePerHead"
    END AS "MarginPct"
FROM "catalog"."Packages" p
JOIN "catalog"."Categories" c ON c."Id" = p."CategoryId"
WHERE p."IsDeleted" = false;

CREATE VIEW "ordering"."vw_KitchenPrep" AS
SELECT o."EventDate", j.value AS "ItemName", COALESCE(o."VariantName", 'Standard') AS "VariantName",
 SUM(o."Guests")::integer AS "TotalHeads", COUNT(*) AS "OrderCount"
FROM "ordering"."Orders" o
CROSS JOIN LATERAL jsonb_array_elements_text(o."SnapshotJson"::jsonb->'items') j(value)
WHERE o."Status" IN ('Confirmed','InPreparation')
GROUP BY o."EventDate", j.value, o."VariantName";

CREATE VIEW "reporting"."vw_OrderSummary" AS
SELECT "Id", "OrderNo", "EventDate", "Status", "PackageName", "CategoryName", "Guests",
 "GrandTotal", "TotalCost", "GrandTotal"-"TotalCost" AS "Profit",
 COALESCE((SELECT SUM(p."Amount") FROM "ordering"."Payments" p WHERE p."OrderId"=o."Id"),0) AS "PaidAmount"
FROM "ordering"."Orders" o;



MERGE INTO "identity"."Permissions" AS t
USING (VALUES
    ('identity.user.view',    'identity',   'View users'),
    ('identity.user.manage',  'identity',   'Create/edit staff users'),
    ('identity.role.view',    'identity',   'View roles'),
    ('identity.role.manage',  'identity',   'Manage roles & grants'),
    ('identity.audit.view',   'identity',   'View audit log'),
    ('nav.menu.view',         'nav',        'View menus'),
    ('nav.menu.manage',       'nav',        'Manage dynamic menus'),
    ('catalog.category.view', 'catalog',    'View categories'),
    ('catalog.category.edit', 'catalog',    'Edit categories'),
    ('catalog.package.view',  'catalog',    'View packages'),
    ('catalog.package.edit',  'catalog',    'Edit packages/items/prices'),
    ('catalog.costing.view',  'catalog',    'View costs & margins'),
    ('ordering.order.view',   'ordering',   'View orders'),
    ('ordering.pricing.view', 'ordering',   'View booking sale amounts and payments'),
    ('ordering.order.manage', 'ordering',   'Create/confirm/cancel orders'),
    ('ordering.kitchen.view', 'ordering',   'Kitchen prep sheet (no money)'),
    ('ordering.payment.record', 'ordering', 'Record manual payments'),
    ('customers.view',        'customers',  'View customers'),
    ('customers.manage',      'customers',  'Manage customers'),
    ('engagement.inquiry.view', 'engagement', 'View inquiries/messages'),
    ('engagement.inquiry.manage', 'engagement', 'Handle inquiries/messages'),
    ('engagement.review.moderate', 'engagement', 'Approve/feature reviews'),
    ('content.view',          'content',    'View CMS content'),
    ('content.edit',          'content',    'Edit CMS content'),
    ('reporting.view',        'reporting',  'View dashboards & reports')
) AS s ("Code", "Module", "Description")
ON t."Code" = s."Code"
WHEN MATCHED THEN UPDATE SET "Module" = s."Module", "Description" = s."Description"
WHEN NOT MATCHED THEN INSERT ("Code", "Module", "Description") VALUES (s."Code", s."Module", s."Description");


MERGE INTO "identity"."Roles" AS t
USING (VALUES
    ('SuperAdmin', 'SUPERADMIN', 'Full system access incl. roles/permissions/menu', 1),
    ('Admin',      'ADMIN',      'Owner: everything except system settings; sees costing', 0),
    ('Manager',    'MANAGER',    'Orders/customers/inquiries/reviews/content; sees costing', 0),
    ('Kitchen',    'KITCHEN',    'Prep sheet + status to InPreparation/Dispatched; no money', 0),
    ('Sales',      'SALES',      'Orders on behalf of customers + inquiries; sale prices only', 0),
    ('Customer',   'CUSTOMER',   'Public + customer endpoints only', 0)
) AS s ("Name", "NormalizedName", "Description", "IsSystem")
ON t."NormalizedName" = s."NormalizedName"
WHEN MATCHED THEN UPDATE SET "Name" = s."Name", "Description" = s."Description", "IsSystem" = (s."IsSystem"::integer <> 0), "UpdatedAt" = timezone('UTC', now())
WHEN NOT MATCHED THEN INSERT ("Id", "Name", "NormalizedName", "Description", "IsSystem") VALUES (gen_random_uuid()::text, s."Name", s."NormalizedName", s."Description", (s."IsSystem"::integer <> 0));



MERGE INTO "identity"."RolePermissions" AS t
USING (
    SELECT r."Id" AS RoleId, p."Id" AS PermissionId
    FROM "identity"."Roles" r CROSS JOIN "identity"."Permissions" p
    WHERE r."NormalizedName" IN ('SUPERADMIN', 'ADMIN')
    UNION
    SELECT r."Id", p."Id" FROM "identity"."Roles" r
    JOIN "identity"."Permissions" p ON p."Code" IN (
        'catalog.category.view', 'catalog.package.view', 'catalog.costing.view',
        'ordering.order.view', 'ordering.order.manage', 'ordering.pricing.view', 'ordering.kitchen.view',
        'customers.view', 'customers.manage',
        'engagement.inquiry.view', 'engagement.inquiry.manage', 'engagement.review.moderate',
        'content.view', 'content.edit', 'reporting.view', 'nav.menu.view')
    WHERE r."NormalizedName" = 'MANAGER'
    UNION
    SELECT r."Id", p."Id" FROM "identity"."Roles" r
    JOIN "identity"."Permissions" p ON p."Code" IN ('ordering.kitchen.view', 'ordering.order.view', 'nav.menu.view')
    WHERE r."NormalizedName" = 'KITCHEN'
    UNION
    SELECT r."Id", p."Id" FROM "identity"."Roles" r
    JOIN "identity"."Permissions" p ON p."Code" IN (
        'catalog.category.view', 'catalog.package.view',
        'ordering.order.view', 'ordering.order.manage', 'ordering.pricing.view',
        'customers.view', 'customers.manage',
        'engagement.inquiry.view', 'engagement.inquiry.manage', 'nav.menu.view')
    WHERE r."NormalizedName" = 'SALES'
) AS s (RoleId, PermissionId)
ON t."RoleId" = s.roleid AND t."PermissionId" = s.permissionid
WHEN NOT MATCHED THEN INSERT ("RoleId", "PermissionId") VALUES (s.roleid, s.permissionid);

DELETE FROM "identity"."RolePermissions" t
WHERE NOT EXISTS (
    SELECT 1 FROM (
        SELECT r."Id" AS RoleId, p."Id" AS PermissionId
        FROM "identity"."Roles" r CROSS JOIN "identity"."Permissions" p
        WHERE r."NormalizedName" IN ('SUPERADMIN', 'ADMIN')
        UNION
        SELECT r."Id", p."Id" FROM "identity"."Roles" r
        JOIN "identity"."Permissions" p ON p."Code" IN (
            'catalog.category.view', 'catalog.package.view', 'catalog.costing.view',
            'ordering.order.view', 'ordering.order.manage', 'ordering.pricing.view', 'ordering.kitchen.view',
            'customers.view', 'customers.manage',
            'engagement.inquiry.view', 'engagement.inquiry.manage', 'engagement.review.moderate',
            'content.view', 'content.edit', 'reporting.view', 'nav.menu.view')
        WHERE r."NormalizedName" = 'MANAGER'
        UNION
        SELECT r."Id", p."Id" FROM "identity"."Roles" r
        JOIN "identity"."Permissions" p ON p."Code" IN ('ordering.kitchen.view', 'ordering.order.view', 'nav.menu.view')
        WHERE r."NormalizedName" = 'KITCHEN'
        UNION
        SELECT r."Id", p."Id" FROM "identity"."Roles" r
        JOIN "identity"."Permissions" p ON p."Code" IN (
            'catalog.category.view', 'catalog.package.view',
            'ordering.order.view', 'ordering.order.manage', 'ordering.pricing.view',
            'customers.view', 'customers.manage',
            'engagement.inquiry.view', 'engagement.inquiry.manage', 'nav.menu.view')
        WHERE r."NormalizedName" = 'SALES'
    ) d WHERE d.RoleId = t."RoleId" AND d.PermissionId = t."PermissionId"
)
AND EXISTS (SELECT 1 FROM "identity"."Roles" r WHERE r."Id" = t."RoleId" AND r."NormalizedName" IN ('MANAGER', 'KITCHEN', 'SALES'));


MERGE INTO "nav"."MenuItems" AS t
USING (VALUES
    ('dashboard',          NULL,                'Dashboard',        'fa-solid fa-gauge',            '/admin',                              NULL,                            'Admin', 10, 1),
    ('orders',             NULL,                'Orders',           'fa-solid fa-receipt',           NULL,                                   'ordering.order.view',        'Admin', 20, 1),
    ('orders.all',         'orders',           'All Orders',       'fa-solid fa-list',              '/admin/orders',                       'ordering.order.view',        'Admin', 21, 1),
    ('orders.calendar',    'orders',           'Calendar',         'fa-solid fa-calendar-days',     '/admin/orders/calendar',              'ordering.order.view',        'Admin', 22, 1),
    ('orders.kitchen',     'orders',           'Kitchen Prep',     'fa-solid fa-kitchen-set',       '/admin/orders/kitchen',               'ordering.kitchen.view',      'Admin', 23, 1),
    ('catalog',            NULL,                'Catalog',          'fa-solid fa-book-open',         NULL,                                   'catalog.package.view',       'Admin', 30, 1),
    ('catalog.packages',   'catalog',          'Packages',         'fa-solid fa-box-open',          '/admin/catalog/packages',             'catalog.package.view',       'Admin', 31, 1),
    ('catalog.costing',    'catalog',          'Costing & Margins','fa-solid fa-calculator',        '/admin/catalog/costing',              'catalog.costing.view',       'Admin', 32, 1),
    ('customers',          NULL,                'Customers',        'fa-solid fa-users',             '/admin/customers',                    'customers.view',             'Admin', 40, 1),
    ('engagement',         NULL,                'Engagement',       'fa-solid fa-comments',          NULL,                                   'engagement.inquiry.view',    'Admin', 50, 1),
    ('engagement.reviews', 'engagement',       'Reviews',          'fa-solid fa-star',              '/admin/engagement/reviews',           'engagement.review.moderate','Admin', 51, 1),
    ('engagement.inbox',   'engagement',       'Customer Inbox',   'fa-solid fa-comments',          '/admin/engagement/requests',          'engagement.inquiry.view',   'Admin', 52, 1),
    ('content',            NULL,                'Website Content',  'fa-solid fa-pen-to-square',     '/admin/content',                      'content.view',               'Admin', 60, 1),
    ('reports',            NULL,                'Reports',          'fa-solid fa-chart-line',        '/admin/reports',                      'reporting.view',             'Admin', 70, 1),
    ('admin',              NULL,                'Administration',   'fa-solid fa-gear',              NULL,                                   'identity.user.view',         'Admin', 80, 1),
    ('admin.menu',         'admin',            'Menu Management',  'fa-solid fa-bars',              '/admin/menu',                         'nav.menu.manage',            'Admin', 81, 1),
    ('admin.audit',        'admin',            'Audit Log',        'fa-solid fa-clock-rotate-left', '/admin/audit',                        'identity.audit.view',        'Admin', 82, 1)
) AS s ("Key", "ParentKey", "Label", "Icon", "Route", "RequiredPermission", "MenuArea", "SortOrder", "IsVisible")
ON t."Key" = s."Key" AND t."MenuArea" = s."MenuArea"
WHEN MATCHED THEN UPDATE SET "Label" = s."Label", "Icon" = s."Icon", "Route" = s."Route",
    "RequiredPermission" = s."RequiredPermission", "SortOrder" = s."SortOrder", "IsVisible" = (s."IsVisible"::integer <> 0), "UpdatedAt" = timezone('UTC', now())
WHEN NOT MATCHED THEN INSERT ("Key", "ParentId", "Label", "Icon", "Route", "RequiredPermission", "MenuArea", "SortOrder", "IsVisible")
    VALUES (s."Key", (SELECT "Id" FROM "nav"."MenuItems" p WHERE p."Key" = s."ParentKey" AND p."MenuArea" = s."MenuArea"), s."Label", s."Icon", s."Route", s."RequiredPermission", s."MenuArea", s."SortOrder", (s."IsVisible"::integer <> 0));

UPDATE "nav"."MenuItems" c SET "ParentId" = p."Id"
FROM "nav"."MenuItems" p
WHERE ((c."Key" = 'orders.all' OR c."Key" = 'orders.calendar' OR c."Key" = 'orders.kitchen') AND p."Key" = 'orders'
   OR (c."Key" = 'catalog.packages' OR c."Key" = 'catalog.costing') AND p."Key" = 'catalog'
   OR (c."Key" IN ('engagement.reviews','engagement.inbox')) AND p."Key" = 'engagement'
   OR (c."Key" = 'admin.menu' OR c."Key" = 'admin.audit') AND p."Key" = 'admin')
AND c."ParentId" IS NULL AND c."Key" <> p."Key";





MERGE INTO "catalog"."Categories" AS t
USING (VALUES
    ('Breakfast', 'breakfast', 10, 1),
    ('Lunch', 'lunch', 20, 1),
    ('Dinner', 'dinner', 30, 1),
    ('Corporate Program', 'corporate-program', 40, 1),
    ('House Party', 'house-party', 50, 1)
) AS s ("Name", "Slug", "SortOrder", "IsActive")
ON t."Name" = s."Name"
WHEN MATCHED THEN UPDATE SET "Slug" = s."Slug", "SortOrder" = s."SortOrder", "IsActive" = (s."IsActive"::integer <> 0), "UpdatedAt" = timezone('UTC', now())
WHEN NOT MATCHED THEN INSERT ("Name", "Slug", "SortOrder", "IsActive") VALUES (s."Name", s."Slug", s."SortOrder", (s."IsActive"::integer <> 0));

MERGE INTO "catalog"."Items" AS t
USING (VALUES
    ('Paratha (2 pcs)', 1),
    ('Vegetable Bhaji', 1),
    ('Scrambled Egg', 1),
    ('Chola Dal', 1),
    ('Sweet', 1),
    ('Black Tea', 1),
    ('Luchi or Paratha', 1),
    ('Aloo Dum', 1),
    ('Egg Curry', 1),
    ('Boot Dal', 1),
    ('Semolina Halwa', 1),
    ('Seasonal Fruit', 1),
    ('Doi-Chira (Yogurt & Flattened Rice)', 1),
    ('Tea / Coffee', 1),
    ('Bhuna Khichuri', 1),
    ('Beef Bhuna', 1),
    ('Fried Eggplant', 1),
    ('Borhani', 1),
    ('Salad', 1),
    ('Jilapi / Sweet', 1),
    ('White Rice', 1),
    ('Chicken Curry', 1),
    ('Masoor Dal', 1),
    ('Mixed Vegetables', 1),
    ('Aloo Bhorta (Mashed Potato)', 1),
    ('Pickle', 1),
    ('Rice / Polao', 1),
    ('Chicken Roast', 1),
    ('Fried Rui Fish', 1),
    ('Dal', 1),
    ('Vegetables', 1),
    ('Sweet Yogurt', 1),
    ('Paan-Supari', 1),
    ('Kacchi Biryani (Mutton/Chicken)', 1),
    ('Egg', 1),
    ('Shahi Zarda', 1),
    ('Polao', 1),
    ('Chicken Rezala', 1),
    ('Beef Rezala', 1),
    ('Hilsa / Rui Fish', 1),
    ('Firni', 1),
    ('Morog Polao / Kacchi', 1),
    ('Beef Kala Bhuna', 1),
    ('Mutton Rezala', 1),
    ('Fried Fish', 1),
    ('Shahi Tukra', 1),
    ('Fruit Platter', 1),
    ('Samosa', 1),
    ('Singara', 1),
    ('Chicken Pakora', 1),
    ('Biscuits', 1),
    ('Water', 1),
    ('Polao / Rice', 1),
    ('Mineral Water', 1),
    ('Rice & Polao', 1),
    ('2 Chicken & Beef Dishes', 1),
    ('Fish', 1),
    ('Salad Bar', 1),
    ('Dessert', 1),
    ('Soft Drink', 1),
    ('Kacchi / Biryani', 1),
    ('Roast', 1),
    ('Kebab Station', 1),
    ('Soup', 1),
    ('Beverages', 1),
    ('Tea/Coffee Corner', 1),
    ('Chicken Fry', 1),
    ('Shawarma / Roll', 1),
    ('Fuchka / Chotpoti', 1),
    ('French Fries', 1),
    ('Spring Roll', 1),
    ('Fish Fry', 1),
    ('Chicken / Beef BBQ', 1),
    ('Grilled Kebab', 1),
    ('Naan', 1),
    ('Dip Sauce', 1)
) AS s ("Name", "IsActive")
ON t."Name" = s."Name"
WHEN MATCHED THEN UPDATE SET "IsActive" = (s."IsActive"::integer <> 0), "UpdatedAt" = timezone('UTC', now())
WHEN NOT MATCHED THEN INSERT ("Name", "IsActive") VALUES (s."Name", (s."IsActive"::integer <> 0));

MERGE INTO "catalog"."AddOns" AS t
USING (VALUES
    ('Outdoor Setup', 'Outdoor setup for BBQ / house parties (admin must set price)', 'Flat', 0, 0, 0),
    ('Live Chef Service', 'Live chef service for BBQ / house parties (admin must set price)', 'PerHead', 0, 0, 0)
) AS s ("Name", "Description", "PricingType", "Price", "Cost", "IsActive")
ON t."Name" = s."Name"
WHEN MATCHED THEN UPDATE SET "Description" = s."Description", "PricingType" = s."PricingType", "UpdatedAt" = timezone('UTC', now())
WHEN NOT MATCHED THEN INSERT ("Name", "Description", "PricingType", "Price", "Cost", "IsActive") VALUES (s."Name", s."Description", s."PricingType", s."Price", s."Cost", (s."IsActive"::integer <> 0));

MERGE INTO "catalog"."Packages" AS t
USING (VALUES
    ('Breakfast', 'Classic Breakfast', 'breakfast-classic-breakfast', NULL, 120.00, 1, 10, 0, 1),
    ('Breakfast', 'Premium Breakfast', 'breakfast-premium-breakfast', NULL, 180.00, 1, 20, 0, 1),
    ('Breakfast', 'Royal Breakfast', 'breakfast-royal-breakfast', NULL, 250.00, 1, 30, 0, 1),
    ('Lunch', 'Standard', 'lunch-standard', NULL, 250.00, 1, 40, 0, 1),
    ('Lunch', 'Premium', 'lunch-premium', NULL, 350.00, 1, 50, 0, 1),
    ('Lunch', 'Royal Kacchi', 'lunch-royal-kacchi', NULL, 500.00, 1, 60, 0, 1),
    ('Dinner', 'Standard', 'dinner-standard', NULL, 280.00, 1, 70, 0, 1),
    ('Dinner', 'Premium', 'dinner-premium', NULL, 400.00, 1, 80, 0, 1),
    ('Dinner', 'Royal Dinner', 'dinner-royal-dinner', NULL, 550.00, 1, 90, 0, 1),
    ('Corporate Program', 'Snacks / Tea Break Package', 'corporate-program-snacks-tea-break-package', 'Ideal for morning or afternoon meeting breaks', 80.00, 1, 100, 0, 1),
    ('Corporate Program', 'Box Lunch', 'corporate-program-box-lunch', NULL, 220.00, 1, 110, 0, 1),
    ('Corporate Program', 'Standard Buffet', 'corporate-program-standard-buffet', NULL, 380.00, 40, 120, 0, 1),
    ('Corporate Program', 'Executive Buffet', 'corporate-program-executive-buffet', NULL, 550.00, 1, 130, 0, 1),
    ('House Party', 'Snacks Party', 'house-party-snacks-party', NULL, 200.00, 1, 140, 0, 1),
    ('House Party', 'Full Dinner Party', 'house-party-full-dinner-party', NULL, 420.00, 1, 150, 0, 1),
    ('House Party', 'BBQ Night', 'house-party-bbq-night', 'Outdoor setup & live chef service available (extra charges apply)', 650.00, 1, 160, 0, 1)
) AS s ("CategoryName", "Name", "Slug", "Tagline", "SalePricePerHead", "MinGuests", "SortOrder", "IsFeatured", "IsActive")
ON t."Slug" = s."Slug"
WHEN MATCHED THEN UPDATE SET "CategoryId" = (SELECT "Id" FROM "catalog"."Categories" WHERE "Name" = s."CategoryName"),
    "Name" = s."Name", "Tagline" = s."Tagline", "SalePricePerHead" = s."SalePricePerHead", "MinGuests" = s."MinGuests",
    "SortOrder" = s."SortOrder", "IsActive" = (s."IsActive"::integer <> 0), "UpdatedAt" = timezone('UTC', now())
WHEN NOT MATCHED THEN INSERT ("CategoryId", "Name", "Slug", "Tagline", "SalePricePerHead", "MinGuests", "SortOrder", "IsFeatured", "IsActive")
    VALUES ((SELECT "Id" FROM "catalog"."Categories" WHERE "Name" = s."CategoryName"), s."Name", s."Slug", s."Tagline", s."SalePricePerHead", s."MinGuests", s."SortOrder", (s."IsFeatured"::integer <> 0), (s."IsActive"::integer <> 0));

DELETE FROM "catalog"."PackageItems" pi USING "catalog"."Packages" p WHERE p."Id" = pi."PackageId" AND p."Slug" IN ('breakfast-classic-breakfast', 'breakfast-premium-breakfast', 'breakfast-royal-breakfast', 'lunch-standard', 'lunch-premium', 'lunch-royal-kacchi', 'dinner-standard', 'dinner-premium', 'dinner-royal-dinner', 'corporate-program-snacks-tea-break-package', 'corporate-program-box-lunch', 'corporate-program-standard-buffet', 'corporate-program-executive-buffet', 'house-party-snacks-party', 'house-party-full-dinner-party', 'house-party-bbq-night');
INSERT INTO "catalog"."PackageItems" ("PackageId", "ItemId", "CostPerHead", "DisplayName", "SortOrder") VALUES
    ((SELECT "Id" FROM "catalog"."Packages" WHERE "Slug" = 'breakfast-classic-breakfast'), (SELECT "Id" FROM "catalog"."Items" WHERE "Name" = 'Paratha (2 pcs)'), 20.00, 'Paratha (2 pcs)', 10),
    ((SELECT "Id" FROM "catalog"."Packages" WHERE "Slug" = 'breakfast-classic-breakfast'), (SELECT "Id" FROM "catalog"."Items" WHERE "Name" = 'Vegetable Bhaji'), 10.00, 'Vegetable Bhaji', 20),
    ((SELECT "Id" FROM "catalog"."Packages" WHERE "Slug" = 'breakfast-classic-breakfast'), (SELECT "Id" FROM "catalog"."Items" WHERE "Name" = 'Scrambled Egg'), 10.00, 'Scrambled Egg', 30),
    ((SELECT "Id" FROM "catalog"."Packages" WHERE "Slug" = 'breakfast-classic-breakfast'), (SELECT "Id" FROM "catalog"."Items" WHERE "Name" = 'Chola Dal'), 10.00, 'Chola Dal', 40),
    ((SELECT "Id" FROM "catalog"."Packages" WHERE "Slug" = 'breakfast-classic-breakfast'), (SELECT "Id" FROM "catalog"."Items" WHERE "Name" = 'Sweet'), 10.00, 'Sweet', 50),
    ((SELECT "Id" FROM "catalog"."Packages" WHERE "Slug" = 'breakfast-classic-breakfast'), (SELECT "Id" FROM "catalog"."Items" WHERE "Name" = 'Black Tea'), 10.00, 'Black Tea', 60),
    ((SELECT "Id" FROM "catalog"."Packages" WHERE "Slug" = 'breakfast-premium-breakfast'), (SELECT "Id" FROM "catalog"."Items" WHERE "Name" = 'Luchi or Paratha'), 25.00, 'Luchi or Paratha', 10),
    ((SELECT "Id" FROM "catalog"."Packages" WHERE "Slug" = 'breakfast-premium-breakfast'), (SELECT "Id" FROM "catalog"."Items" WHERE "Name" = 'Aloo Dum'), 15.00, 'Aloo Dum', 20),
    ((SELECT "Id" FROM "catalog"."Packages" WHERE "Slug" = 'breakfast-premium-breakfast'), (SELECT "Id" FROM "catalog"."Items" WHERE "Name" = 'Egg Curry'), 15.00, 'Egg Curry', 30),
    ((SELECT "Id" FROM "catalog"."Packages" WHERE "Slug" = 'breakfast-premium-breakfast'), (SELECT "Id" FROM "catalog"."Items" WHERE "Name" = 'Boot Dal'), 10.00, 'Boot Dal', 40),
    ((SELECT "Id" FROM "catalog"."Packages" WHERE "Slug" = 'breakfast-premium-breakfast'), (SELECT "Id" FROM "catalog"."Items" WHERE "Name" = 'Semolina Halwa'), 15.00, 'Semolina Halwa', 50),
    ((SELECT "Id" FROM "catalog"."Packages" WHERE "Slug" = 'breakfast-premium-breakfast'), (SELECT "Id" FROM "catalog"."Items" WHERE "Name" = 'Seasonal Fruit'), 10.00, 'Seasonal Fruit', 60),
    ((SELECT "Id" FROM "catalog"."Packages" WHERE "Slug" = 'breakfast-premium-breakfast'), (SELECT "Id" FROM "catalog"."Items" WHERE "Name" = 'Doi-Chira (Yogurt & Flattened Rice)'), 10.00, 'Doi-Chira (Yogurt & Flattened Rice)', 70),
    ((SELECT "Id" FROM "catalog"."Packages" WHERE "Slug" = 'breakfast-premium-breakfast'), (SELECT "Id" FROM "catalog"."Items" WHERE "Name" = 'Tea / Coffee'), 5.00, 'Tea / Coffee', 80),
    ((SELECT "Id" FROM "catalog"."Packages" WHERE "Slug" = 'breakfast-royal-breakfast'), (SELECT "Id" FROM "catalog"."Items" WHERE "Name" = 'Bhuna Khichuri'), 30.00, 'Bhuna Khichuri', 10),
    ((SELECT "Id" FROM "catalog"."Packages" WHERE "Slug" = 'breakfast-royal-breakfast'), (SELECT "Id" FROM "catalog"."Items" WHERE "Name" = 'Beef Bhuna'), 50.00, 'Beef Bhuna', 20),
    ((SELECT "Id" FROM "catalog"."Packages" WHERE "Slug" = 'breakfast-royal-breakfast'), (SELECT "Id" FROM "catalog"."Items" WHERE "Name" = 'Egg Curry'), 15.00, 'Egg Curry', 30),
    ((SELECT "Id" FROM "catalog"."Packages" WHERE "Slug" = 'breakfast-royal-breakfast'), (SELECT "Id" FROM "catalog"."Items" WHERE "Name" = 'Fried Eggplant'), 10.00, 'Fried Eggplant', 40),
    ((SELECT "Id" FROM "catalog"."Packages" WHERE "Slug" = 'breakfast-royal-breakfast'), (SELECT "Id" FROM "catalog"."Items" WHERE "Name" = 'Borhani'), 15.00, 'Borhani', 50),
    ((SELECT "Id" FROM "catalog"."Packages" WHERE "Slug" = 'breakfast-royal-breakfast'), (SELECT "Id" FROM "catalog"."Items" WHERE "Name" = 'Salad'), 5.00, 'Salad', 60),
    ((SELECT "Id" FROM "catalog"."Packages" WHERE "Slug" = 'breakfast-royal-breakfast'), (SELECT "Id" FROM "catalog"."Items" WHERE "Name" = 'Jilapi / Sweet'), 15.00, 'Jilapi / Sweet', 70),
    ((SELECT "Id" FROM "catalog"."Packages" WHERE "Slug" = 'breakfast-royal-breakfast'), (SELECT "Id" FROM "catalog"."Items" WHERE "Name" = 'Tea / Coffee'), 5.00, 'Tea / Coffee', 80),
    ((SELECT "Id" FROM "catalog"."Packages" WHERE "Slug" = 'lunch-standard'), (SELECT "Id" FROM "catalog"."Items" WHERE "Name" = 'White Rice'), 20.00, 'White Rice', 10),
    ((SELECT "Id" FROM "catalog"."Packages" WHERE "Slug" = 'lunch-standard'), (SELECT "Id" FROM "catalog"."Items" WHERE "Name" = 'Chicken Curry'), 75.00, 'Chicken Curry', 20),
    ((SELECT "Id" FROM "catalog"."Packages" WHERE "Slug" = 'lunch-standard'), (SELECT "Id" FROM "catalog"."Items" WHERE "Name" = 'Masoor Dal'), 15.00, 'Masoor Dal', 30),
    ((SELECT "Id" FROM "catalog"."Packages" WHERE "Slug" = 'lunch-standard'), (SELECT "Id" FROM "catalog"."Items" WHERE "Name" = 'Mixed Vegetables'), 15.00, 'Mixed Vegetables', 40),
    ((SELECT "Id" FROM "catalog"."Packages" WHERE "Slug" = 'lunch-standard'), (SELECT "Id" FROM "catalog"."Items" WHERE "Name" = 'Aloo Bhorta (Mashed Potato)'), 10.00, 'Aloo Bhorta (Mashed Potato)', 50),
    ((SELECT "Id" FROM "catalog"."Packages" WHERE "Slug" = 'lunch-standard'), (SELECT "Id" FROM "catalog"."Items" WHERE "Name" = 'Salad'), 5.00, 'Salad', 60),
    ((SELECT "Id" FROM "catalog"."Packages" WHERE "Slug" = 'lunch-standard'), (SELECT "Id" FROM "catalog"."Items" WHERE "Name" = 'Pickle'), 5.00, 'Pickle', 70),
    ((SELECT "Id" FROM "catalog"."Packages" WHERE "Slug" = 'lunch-premium'), (SELECT "Id" FROM "catalog"."Items" WHERE "Name" = 'Rice / Polao'), 25.00, 'Rice / Polao', 10),
    ((SELECT "Id" FROM "catalog"."Packages" WHERE "Slug" = 'lunch-premium'), (SELECT "Id" FROM "catalog"."Items" WHERE "Name" = 'Chicken Roast'), 50.00, 'Chicken Roast', 20),
    ((SELECT "Id" FROM "catalog"."Packages" WHERE "Slug" = 'lunch-premium'), (SELECT "Id" FROM "catalog"."Items" WHERE "Name" = 'Beef Bhuna'), 60.00, 'Beef Bhuna', 30),
    ((SELECT "Id" FROM "catalog"."Packages" WHERE "Slug" = 'lunch-premium'), (SELECT "Id" FROM "catalog"."Items" WHERE "Name" = 'Fried Rui Fish'), 35.00, 'Fried Rui Fish', 40),
    ((SELECT "Id" FROM "catalog"."Packages" WHERE "Slug" = 'lunch-premium'), (SELECT "Id" FROM "catalog"."Items" WHERE "Name" = 'Dal'), 10.00, 'Dal', 50),
    ((SELECT "Id" FROM "catalog"."Packages" WHERE "Slug" = 'lunch-premium'), (SELECT "Id" FROM "catalog"."Items" WHERE "Name" = 'Vegetables'), 10.00, 'Vegetables', 60),
    ((SELECT "Id" FROM "catalog"."Packages" WHERE "Slug" = 'lunch-premium'), (SELECT "Id" FROM "catalog"."Items" WHERE "Name" = 'Salad'), 5.00, 'Salad', 70),
    ((SELECT "Id" FROM "catalog"."Packages" WHERE "Slug" = 'lunch-premium'), (SELECT "Id" FROM "catalog"."Items" WHERE "Name" = 'Sweet Yogurt'), 5.00, 'Sweet Yogurt', 80),
    ((SELECT "Id" FROM "catalog"."Packages" WHERE "Slug" = 'lunch-premium'), (SELECT "Id" FROM "catalog"."Items" WHERE "Name" = 'Paan-Supari'), 5.00, 'Paan-Supari', 90),
    ((SELECT "Id" FROM "catalog"."Packages" WHERE "Slug" = 'lunch-royal-kacchi'), (SELECT "Id" FROM "catalog"."Items" WHERE "Name" = 'Kacchi Biryani (Mutton/Chicken)'), 205.00, 'Kacchi Biryani (Mutton/Chicken)', 10),
    ((SELECT "Id" FROM "catalog"."Packages" WHERE "Slug" = 'lunch-royal-kacchi'), (SELECT "Id" FROM "catalog"."Items" WHERE "Name" = 'Borhani'), 25.00, 'Borhani', 20),
    ((SELECT "Id" FROM "catalog"."Packages" WHERE "Slug" = 'lunch-royal-kacchi'), (SELECT "Id" FROM "catalog"."Items" WHERE "Name" = 'Salad'), 10.00, 'Salad', 30),
    ((SELECT "Id" FROM "catalog"."Packages" WHERE "Slug" = 'lunch-royal-kacchi'), (SELECT "Id" FROM "catalog"."Items" WHERE "Name" = 'Egg'), 15.00, 'Egg', 40),
    ((SELECT "Id" FROM "catalog"."Packages" WHERE "Slug" = 'lunch-royal-kacchi'), (SELECT "Id" FROM "catalog"."Items" WHERE "Name" = 'Fried Eggplant'), 10.00, 'Fried Eggplant', 50),
    ((SELECT "Id" FROM "catalog"."Packages" WHERE "Slug" = 'lunch-royal-kacchi'), (SELECT "Id" FROM "catalog"."Items" WHERE "Name" = 'Shahi Zarda'), 20.00, 'Shahi Zarda', 60),
    ((SELECT "Id" FROM "catalog"."Packages" WHERE "Slug" = 'lunch-royal-kacchi'), (SELECT "Id" FROM "catalog"."Items" WHERE "Name" = 'Sweet'), 10.00, 'Sweet', 70),
    ((SELECT "Id" FROM "catalog"."Packages" WHERE "Slug" = 'lunch-royal-kacchi'), (SELECT "Id" FROM "catalog"."Items" WHERE "Name" = 'Paan-Supari'), 5.00, 'Paan-Supari', 80),
    ((SELECT "Id" FROM "catalog"."Packages" WHERE "Slug" = 'dinner-standard'), (SELECT "Id" FROM "catalog"."Items" WHERE "Name" = 'Polao'), 25.00, 'Polao', 10),
    ((SELECT "Id" FROM "catalog"."Packages" WHERE "Slug" = 'dinner-standard'), (SELECT "Id" FROM "catalog"."Items" WHERE "Name" = 'Chicken Rezala'), 90.00, 'Chicken Rezala', 20),
    ((SELECT "Id" FROM "catalog"."Packages" WHERE "Slug" = 'dinner-standard'), (SELECT "Id" FROM "catalog"."Items" WHERE "Name" = 'Dal'), 15.00, 'Dal', 30),
    ((SELECT "Id" FROM "catalog"."Packages" WHERE "Slug" = 'dinner-standard'), (SELECT "Id" FROM "catalog"."Items" WHERE "Name" = 'Vegetables'), 15.00, 'Vegetables', 40),
    ((SELECT "Id" FROM "catalog"."Packages" WHERE "Slug" = 'dinner-standard'), (SELECT "Id" FROM "catalog"."Items" WHERE "Name" = 'Salad'), 5.00, 'Salad', 50),
    ((SELECT "Id" FROM "catalog"."Packages" WHERE "Slug" = 'dinner-standard'), (SELECT "Id" FROM "catalog"."Items" WHERE "Name" = 'Pickle'), 5.00, 'Pickle', 60),
    ((SELECT "Id" FROM "catalog"."Packages" WHERE "Slug" = 'dinner-standard'), (SELECT "Id" FROM "catalog"."Items" WHERE "Name" = 'Sweet'), 10.00, 'Sweet', 70),
    ((SELECT "Id" FROM "catalog"."Packages" WHERE "Slug" = 'dinner-premium'), (SELECT "Id" FROM "catalog"."Items" WHERE "Name" = 'Polao'), 30.00, 'Polao', 10),
    ((SELECT "Id" FROM "catalog"."Packages" WHERE "Slug" = 'dinner-premium'), (SELECT "Id" FROM "catalog"."Items" WHERE "Name" = 'Chicken Roast'), 55.00, 'Chicken Roast', 20),
    ((SELECT "Id" FROM "catalog"."Packages" WHERE "Slug" = 'dinner-premium'), (SELECT "Id" FROM "catalog"."Items" WHERE "Name" = 'Beef Rezala'), 70.00, 'Beef Rezala', 30),
    ((SELECT "Id" FROM "catalog"."Packages" WHERE "Slug" = 'dinner-premium'), (SELECT "Id" FROM "catalog"."Items" WHERE "Name" = 'Hilsa / Rui Fish'), 35.00, 'Hilsa / Rui Fish', 40),
    ((SELECT "Id" FROM "catalog"."Packages" WHERE "Slug" = 'dinner-premium'), (SELECT "Id" FROM "catalog"."Items" WHERE "Name" = 'Dal'), 10.00, 'Dal', 50),
    ((SELECT "Id" FROM "catalog"."Packages" WHERE "Slug" = 'dinner-premium'), (SELECT "Id" FROM "catalog"."Items" WHERE "Name" = 'Vegetables'), 10.00, 'Vegetables', 60),
    ((SELECT "Id" FROM "catalog"."Packages" WHERE "Slug" = 'dinner-premium'), (SELECT "Id" FROM "catalog"."Items" WHERE "Name" = 'Salad'), 5.00, 'Salad', 70),
    ((SELECT "Id" FROM "catalog"."Packages" WHERE "Slug" = 'dinner-premium'), (SELECT "Id" FROM "catalog"."Items" WHERE "Name" = 'Borhani'), 15.00, 'Borhani', 80),
    ((SELECT "Id" FROM "catalog"."Packages" WHERE "Slug" = 'dinner-premium'), (SELECT "Id" FROM "catalog"."Items" WHERE "Name" = 'Firni'), 5.00, 'Firni', 90),
    ((SELECT "Id" FROM "catalog"."Packages" WHERE "Slug" = 'dinner-royal-dinner'), (SELECT "Id" FROM "catalog"."Items" WHERE "Name" = 'Morog Polao / Kacchi'), 75.00, 'Morog Polao / Kacchi', 10),
    ((SELECT "Id" FROM "catalog"."Packages" WHERE "Slug" = 'dinner-royal-dinner'), (SELECT "Id" FROM "catalog"."Items" WHERE "Name" = 'Beef Kala Bhuna'), 75.00, 'Beef Kala Bhuna', 20),
    ((SELECT "Id" FROM "catalog"."Packages" WHERE "Slug" = 'dinner-royal-dinner'), (SELECT "Id" FROM "catalog"."Items" WHERE "Name" = 'Mutton Rezala'), 85.00, 'Mutton Rezala', 30),
    ((SELECT "Id" FROM "catalog"."Packages" WHERE "Slug" = 'dinner-royal-dinner'), (SELECT "Id" FROM "catalog"."Items" WHERE "Name" = 'Fried Fish'), 35.00, 'Fried Fish', 40),
    ((SELECT "Id" FROM "catalog"."Packages" WHERE "Slug" = 'dinner-royal-dinner'), (SELECT "Id" FROM "catalog"."Items" WHERE "Name" = 'Dal'), 10.00, 'Dal', 50),
    ((SELECT "Id" FROM "catalog"."Packages" WHERE "Slug" = 'dinner-royal-dinner'), (SELECT "Id" FROM "catalog"."Items" WHERE "Name" = 'Borhani'), 15.00, 'Borhani', 60),
    ((SELECT "Id" FROM "catalog"."Packages" WHERE "Slug" = 'dinner-royal-dinner'), (SELECT "Id" FROM "catalog"."Items" WHERE "Name" = 'Salad'), 5.00, 'Salad', 70),
    ((SELECT "Id" FROM "catalog"."Packages" WHERE "Slug" = 'dinner-royal-dinner'), (SELECT "Id" FROM "catalog"."Items" WHERE "Name" = 'Shahi Tukra'), 15.00, 'Shahi Tukra', 80),
    ((SELECT "Id" FROM "catalog"."Packages" WHERE "Slug" = 'dinner-royal-dinner'), (SELECT "Id" FROM "catalog"."Items" WHERE "Name" = 'Fruit Platter'), 5.00, 'Fruit Platter', 90),
    ((SELECT "Id" FROM "catalog"."Packages" WHERE "Slug" = 'corporate-program-snacks-tea-break-package'), (SELECT "Id" FROM "catalog"."Items" WHERE "Name" = 'Samosa'), 10.00, 'Samosa', 10),
    ((SELECT "Id" FROM "catalog"."Packages" WHERE "Slug" = 'corporate-program-snacks-tea-break-package'), (SELECT "Id" FROM "catalog"."Items" WHERE "Name" = 'Singara'), 10.00, 'Singara', 20),
    ((SELECT "Id" FROM "catalog"."Packages" WHERE "Slug" = 'corporate-program-snacks-tea-break-package'), (SELECT "Id" FROM "catalog"."Items" WHERE "Name" = 'Chicken Pakora'), 15.00, 'Chicken Pakora', 30),
    ((SELECT "Id" FROM "catalog"."Packages" WHERE "Slug" = 'corporate-program-snacks-tea-break-package'), (SELECT "Id" FROM "catalog"."Items" WHERE "Name" = 'Biscuits'), 5.00, 'Biscuits', 40),
    ((SELECT "Id" FROM "catalog"."Packages" WHERE "Slug" = 'corporate-program-snacks-tea-break-package'), (SELECT "Id" FROM "catalog"."Items" WHERE "Name" = 'Tea / Coffee'), 3.00, 'Tea / Coffee', 50),
    ((SELECT "Id" FROM "catalog"."Packages" WHERE "Slug" = 'corporate-program-snacks-tea-break-package'), (SELECT "Id" FROM "catalog"."Items" WHERE "Name" = 'Water'), 2.00, 'Water', 60),
    ((SELECT "Id" FROM "catalog"."Packages" WHERE "Slug" = 'corporate-program-box-lunch'), (SELECT "Id" FROM "catalog"."Items" WHERE "Name" = 'Polao / Rice'), 20.00, 'Polao / Rice', 10),
    ((SELECT "Id" FROM "catalog"."Packages" WHERE "Slug" = 'corporate-program-box-lunch'), (SELECT "Id" FROM "catalog"."Items" WHERE "Name" = 'Chicken Curry'), 80.00, 'Chicken Curry', 20),
    ((SELECT "Id" FROM "catalog"."Packages" WHERE "Slug" = 'corporate-program-box-lunch'), (SELECT "Id" FROM "catalog"."Items" WHERE "Name" = 'Dal'), 10.00, 'Dal', 30),
    ((SELECT "Id" FROM "catalog"."Packages" WHERE "Slug" = 'corporate-program-box-lunch'), (SELECT "Id" FROM "catalog"."Items" WHERE "Name" = 'Vegetables'), 10.00, 'Vegetables', 40),
    ((SELECT "Id" FROM "catalog"."Packages" WHERE "Slug" = 'corporate-program-box-lunch'), (SELECT "Id" FROM "catalog"."Items" WHERE "Name" = 'Salad'), 5.00, 'Salad', 50),
    ((SELECT "Id" FROM "catalog"."Packages" WHERE "Slug" = 'corporate-program-box-lunch'), (SELECT "Id" FROM "catalog"."Items" WHERE "Name" = 'Mineral Water'), 5.00, 'Mineral Water', 60),
    ((SELECT "Id" FROM "catalog"."Packages" WHERE "Slug" = 'corporate-program-standard-buffet'), (SELECT "Id" FROM "catalog"."Items" WHERE "Name" = 'Rice & Polao'), 25.00, 'Rice & Polao', 10),
    ((SELECT "Id" FROM "catalog"."Packages" WHERE "Slug" = 'corporate-program-standard-buffet'), (SELECT "Id" FROM "catalog"."Items" WHERE "Name" = '2 Chicken & Beef Dishes'), 110.00, '2 Chicken & Beef Dishes', 20),
    ((SELECT "Id" FROM "catalog"."Packages" WHERE "Slug" = 'corporate-program-standard-buffet'), (SELECT "Id" FROM "catalog"."Items" WHERE "Name" = 'Fish'), 30.00, 'Fish', 30),
    ((SELECT "Id" FROM "catalog"."Packages" WHERE "Slug" = 'corporate-program-standard-buffet'), (SELECT "Id" FROM "catalog"."Items" WHERE "Name" = 'Dal'), 10.00, 'Dal', 40),
    ((SELECT "Id" FROM "catalog"."Packages" WHERE "Slug" = 'corporate-program-standard-buffet'), (SELECT "Id" FROM "catalog"."Items" WHERE "Name" = 'Vegetables'), 10.00, 'Vegetables', 50),
    ((SELECT "Id" FROM "catalog"."Packages" WHERE "Slug" = 'corporate-program-standard-buffet'), (SELECT "Id" FROM "catalog"."Items" WHERE "Name" = 'Salad Bar'), 10.00, 'Salad Bar', 60),
    ((SELECT "Id" FROM "catalog"."Packages" WHERE "Slug" = 'corporate-program-standard-buffet'), (SELECT "Id" FROM "catalog"."Items" WHERE "Name" = 'Dessert'), 15.00, 'Dessert', 70),
    ((SELECT "Id" FROM "catalog"."Packages" WHERE "Slug" = 'corporate-program-standard-buffet'), (SELECT "Id" FROM "catalog"."Items" WHERE "Name" = 'Soft Drink'), 10.00, 'Soft Drink', 80),
    ((SELECT "Id" FROM "catalog"."Packages" WHERE "Slug" = 'corporate-program-executive-buffet'), (SELECT "Id" FROM "catalog"."Items" WHERE "Name" = 'Kacchi / Biryani'), 90.00, 'Kacchi / Biryani', 10),
    ((SELECT "Id" FROM "catalog"."Packages" WHERE "Slug" = 'corporate-program-executive-buffet'), (SELECT "Id" FROM "catalog"."Items" WHERE "Name" = 'Roast'), 70.00, 'Roast', 20),
    ((SELECT "Id" FROM "catalog"."Packages" WHERE "Slug" = 'corporate-program-executive-buffet'), (SELECT "Id" FROM "catalog"."Items" WHERE "Name" = 'Kebab Station'), 60.00, 'Kebab Station', 30),
    ((SELECT "Id" FROM "catalog"."Packages" WHERE "Slug" = 'corporate-program-executive-buffet'), (SELECT "Id" FROM "catalog"."Items" WHERE "Name" = 'Fish'), 35.00, 'Fish', 40),
    ((SELECT "Id" FROM "catalog"."Packages" WHERE "Slug" = 'corporate-program-executive-buffet'), (SELECT "Id" FROM "catalog"."Items" WHERE "Name" = 'Salad Bar'), 15.00, 'Salad Bar', 50),
    ((SELECT "Id" FROM "catalog"."Packages" WHERE "Slug" = 'corporate-program-executive-buffet'), (SELECT "Id" FROM "catalog"."Items" WHERE "Name" = 'Soup'), 15.00, 'Soup', 60),
    ((SELECT "Id" FROM "catalog"."Packages" WHERE "Slug" = 'corporate-program-executive-buffet'), (SELECT "Id" FROM "catalog"."Items" WHERE "Name" = 'Dessert'), 15.00, 'Dessert', 70),
    ((SELECT "Id" FROM "catalog"."Packages" WHERE "Slug" = 'corporate-program-executive-buffet'), (SELECT "Id" FROM "catalog"."Items" WHERE "Name" = 'Beverages'), 15.00, 'Beverages', 80),
    ((SELECT "Id" FROM "catalog"."Packages" WHERE "Slug" = 'corporate-program-executive-buffet'), (SELECT "Id" FROM "catalog"."Items" WHERE "Name" = 'Tea/Coffee Corner'), 5.00, 'Tea/Coffee Corner', 90),
    ((SELECT "Id" FROM "catalog"."Packages" WHERE "Slug" = 'house-party-snacks-party'), (SELECT "Id" FROM "catalog"."Items" WHERE "Name" = 'Chicken Fry'), 35.00, 'Chicken Fry', 10),
    ((SELECT "Id" FROM "catalog"."Packages" WHERE "Slug" = 'house-party-snacks-party'), (SELECT "Id" FROM "catalog"."Items" WHERE "Name" = 'Shawarma / Roll'), 30.00, 'Shawarma / Roll', 20),
    ((SELECT "Id" FROM "catalog"."Packages" WHERE "Slug" = 'house-party-snacks-party'), (SELECT "Id" FROM "catalog"."Items" WHERE "Name" = 'Fuchka / Chotpoti'), 15.00, 'Fuchka / Chotpoti', 30),
    ((SELECT "Id" FROM "catalog"."Packages" WHERE "Slug" = 'house-party-snacks-party'), (SELECT "Id" FROM "catalog"."Items" WHERE "Name" = 'French Fries'), 15.00, 'French Fries', 40),
    ((SELECT "Id" FROM "catalog"."Packages" WHERE "Slug" = 'house-party-snacks-party'), (SELECT "Id" FROM "catalog"."Items" WHERE "Name" = 'Spring Roll'), 15.00, 'Spring Roll', 50),
    ((SELECT "Id" FROM "catalog"."Packages" WHERE "Slug" = 'house-party-snacks-party'), (SELECT "Id" FROM "catalog"."Items" WHERE "Name" = 'Soft Drink'), 5.00, 'Soft Drink', 60),
    ((SELECT "Id" FROM "catalog"."Packages" WHERE "Slug" = 'house-party-full-dinner-party'), (SELECT "Id" FROM "catalog"."Items" WHERE "Name" = 'Polao'), 30.00, 'Polao', 10),
    ((SELECT "Id" FROM "catalog"."Packages" WHERE "Slug" = 'house-party-full-dinner-party'), (SELECT "Id" FROM "catalog"."Items" WHERE "Name" = 'Chicken Roast'), 60.00, 'Chicken Roast', 20),
    ((SELECT "Id" FROM "catalog"."Packages" WHERE "Slug" = 'house-party-full-dinner-party'), (SELECT "Id" FROM "catalog"."Items" WHERE "Name" = 'Beef Bhuna'), 75.00, 'Beef Bhuna', 30),
    ((SELECT "Id" FROM "catalog"."Packages" WHERE "Slug" = 'house-party-full-dinner-party'), (SELECT "Id" FROM "catalog"."Items" WHERE "Name" = 'Fish Fry'), 40.00, 'Fish Fry', 40),
    ((SELECT "Id" FROM "catalog"."Packages" WHERE "Slug" = 'house-party-full-dinner-party'), (SELECT "Id" FROM "catalog"."Items" WHERE "Name" = 'Dal'), 10.00, 'Dal', 50),
    ((SELECT "Id" FROM "catalog"."Packages" WHERE "Slug" = 'house-party-full-dinner-party'), (SELECT "Id" FROM "catalog"."Items" WHERE "Name" = 'Vegetables'), 10.00, 'Vegetables', 60),
    ((SELECT "Id" FROM "catalog"."Packages" WHERE "Slug" = 'house-party-full-dinner-party'), (SELECT "Id" FROM "catalog"."Items" WHERE "Name" = 'Salad'), 5.00, 'Salad', 70),
    ((SELECT "Id" FROM "catalog"."Packages" WHERE "Slug" = 'house-party-full-dinner-party'), (SELECT "Id" FROM "catalog"."Items" WHERE "Name" = 'Borhani'), 10.00, 'Borhani', 80),
    ((SELECT "Id" FROM "catalog"."Packages" WHERE "Slug" = 'house-party-full-dinner-party'), (SELECT "Id" FROM "catalog"."Items" WHERE "Name" = 'Dessert'), 5.00, 'Dessert', 90),
    ((SELECT "Id" FROM "catalog"."Packages" WHERE "Slug" = 'house-party-bbq-night'), (SELECT "Id" FROM "catalog"."Items" WHERE "Name" = 'Chicken / Beef BBQ'), 180.00, 'Chicken / Beef BBQ', 10),
    ((SELECT "Id" FROM "catalog"."Packages" WHERE "Slug" = 'house-party-bbq-night'), (SELECT "Id" FROM "catalog"."Items" WHERE "Name" = 'Grilled Kebab'), 110.00, 'Grilled Kebab', 20),
    ((SELECT "Id" FROM "catalog"."Packages" WHERE "Slug" = 'house-party-bbq-night'), (SELECT "Id" FROM "catalog"."Items" WHERE "Name" = 'Naan'), 25.00, 'Naan', 30),
    ((SELECT "Id" FROM "catalog"."Packages" WHERE "Slug" = 'house-party-bbq-night'), (SELECT "Id" FROM "catalog"."Items" WHERE "Name" = 'Salad Bar'), 20.00, 'Salad Bar', 40),
    ((SELECT "Id" FROM "catalog"."Packages" WHERE "Slug" = 'house-party-bbq-night'), (SELECT "Id" FROM "catalog"."Items" WHERE "Name" = 'Dip Sauce'), 10.00, 'Dip Sauce', 50),
    ((SELECT "Id" FROM "catalog"."Packages" WHERE "Slug" = 'house-party-bbq-night'), (SELECT "Id" FROM "catalog"."Items" WHERE "Name" = 'Soft Drink'), 25.00, 'Soft Drink', 60),
    ((SELECT "Id" FROM "catalog"."Packages" WHERE "Slug" = 'house-party-bbq-night'), (SELECT "Id" FROM "catalog"."Items" WHERE "Name" = 'Dessert'), 10.00, 'Dessert', 70);

DELETE FROM "catalog"."PackageInclusions" i USING "catalog"."Packages" p WHERE p."Id" = i."PackageId" AND p."Slug" IN ('breakfast-classic-breakfast', 'breakfast-premium-breakfast', 'breakfast-royal-breakfast', 'lunch-standard', 'lunch-premium', 'lunch-royal-kacchi', 'dinner-standard', 'dinner-premium', 'dinner-royal-dinner', 'corporate-program-snacks-tea-break-package', 'corporate-program-box-lunch', 'corporate-program-standard-buffet', 'corporate-program-executive-buffet', 'house-party-snacks-party', 'house-party-full-dinner-party', 'house-party-bbq-night');
INSERT INTO "catalog"."PackageInclusions" ("PackageId", "Text", "SortOrder") VALUES
    ((SELECT "Id" FROM "catalog"."Packages" WHERE "Slug" = 'corporate-program-executive-buffet'), 'Includes waiter service & cutlery', 10);

DELETE FROM "catalog"."PackageVariants" v USING "catalog"."Packages" p WHERE p."Id" = v."PackageId" AND p."Slug" IN ('breakfast-classic-breakfast', 'breakfast-premium-breakfast', 'breakfast-royal-breakfast', 'lunch-standard', 'lunch-premium', 'lunch-royal-kacchi', 'dinner-standard', 'dinner-premium', 'dinner-royal-dinner', 'corporate-program-snacks-tea-break-package', 'corporate-program-box-lunch', 'corporate-program-standard-buffet', 'corporate-program-executive-buffet', 'house-party-snacks-party', 'house-party-full-dinner-party', 'house-party-bbq-night');
INSERT INTO "catalog"."PackageVariants" ("PackageId", "Name", "PriceDeltaPerHead", "CostDeltaPerHead", "IsDefault") VALUES
    ((SELECT "Id" FROM "catalog"."Packages" WHERE "Slug" = 'lunch-royal-kacchi'), 'Chicken', 0.00, 0, true),
    ((SELECT "Id" FROM "catalog"."Packages" WHERE "Slug" = 'lunch-royal-kacchi'), 'Mutton', 80.00, 0, false);

DELETE FROM "catalog"."PackageAddOns" pa USING "catalog"."Packages" p WHERE p."Id" = pa."PackageId" AND p."Slug" IN ('breakfast-classic-breakfast', 'breakfast-premium-breakfast', 'breakfast-royal-breakfast', 'lunch-standard', 'lunch-premium', 'lunch-royal-kacchi', 'dinner-standard', 'dinner-premium', 'dinner-royal-dinner', 'corporate-program-snacks-tea-break-package', 'corporate-program-box-lunch', 'corporate-program-standard-buffet', 'corporate-program-executive-buffet', 'house-party-snacks-party', 'house-party-full-dinner-party', 'house-party-bbq-night');
INSERT INTO "catalog"."PackageAddOns" ("PackageId", "AddOnId") VALUES
    ((SELECT "Id" FROM "catalog"."Packages" WHERE "Slug" = 'house-party-bbq-night'), (SELECT "Id" FROM "catalog"."AddOns" WHERE "Name" = 'Outdoor Setup')),
    ((SELECT "Id" FROM "catalog"."Packages" WHERE "Slug" = 'house-party-bbq-night'), (SELECT "Id" FROM "catalog"."AddOns" WHERE "Name" = 'Live Chef Service'));
