"""Generate the reviewed PostgreSQL initial schema from the database-first SQL sources.
Run from repository root after SQL source changes; inspect/validate the resulting SQL.
This is a project-specific converter, not a general T-SQL translator.
"""
from pathlib import Path
import re

root = Path('database/ZRC.Database')
out = Path('database/postgresql')
bools = set()
for f in root.glob('*/Tables/*.sql'):
    bools.update(re.findall(r'\[(\w+)\]\s+BIT\b', f.read_text(encoding='utf-8-sig'), re.I))

def convert(s):
    s = re.sub(r'--[^\n]*', '', s)
    s = re.sub(r'^\s*GO\s*$', '', s, flags=re.M)
    s = re.sub(r"(?<![\w'])N(?=')", '', s)
    s = re.sub(r'\[([^\]]+)\]', r'"\1"', s)
    s = re.sub(r'NVARCHAR\(MAX\)', 'text', s, flags=re.I)
    s = re.sub(r'NVARCHAR\((\d+)\)', r'varchar(\1)', s, flags=re.I)
    s = re.sub(r'UNIQUEIDENTIFIER', 'uuid', s, flags=re.I)
    s = re.sub(r'DATETIME2\(\d+\)', 'timestamp without time zone', s, flags=re.I)
    s = re.sub(r'DATETIMEOFFSET(?:\(\d+\))?', 'timestamp with time zone', s, flags=re.I)
    s = re.sub(r'IDENTITY\(1,\s*1\)', 'GENERATED BY DEFAULT AS IDENTITY', s, flags=re.I)
    s = re.sub(r'(BIGINT|INT)\s+IDENTITY\b', r'\1 GENERATED BY DEFAULT AS IDENTITY', s, flags=re.I)
    s = re.sub(r'(?<!")\bROWVERSION\b(?!")', "bytea DEFAULT decode(replace(gen_random_uuid()::text, '-', ''), 'hex')", s, flags=re.I)
    s = re.sub(r'CONSTRAINT "DF_[^"]+"\s+', '', s)
    s = re.sub(r'\bBIT\b', 'boolean', s, flags=re.I)
    s = re.sub(r'\bCLUSTERED\b', '', s, flags=re.I)
    s = re.sub(r'(PRIMARY KEY[^\n]+)', lambda m: m[0].replace(' ASC', ''), s)
    s = re.sub(r'SYSUTCDATETIME\(\)', "timezone('UTC', now())", s, flags=re.I)
    s = re.sub(r'NEWID\(\)', 'gen_random_uuid()', s, flags=re.I)
    s = re.sub(r'ISNULL\(', 'COALESCE(', s, flags=re.I)
    s = re.sub(r'\bLEN\(', 'length(', s, flags=re.I)
    s = re.sub(r'ISJSON\("(\w+)"\)=1', r'("\1"::jsonb IS NOT NULL)', s)
    for b in bools:
        s = re.sub(r'("'+b+r'"\s+boolean\s+NOT NULL\s+DEFAULT\s*)\(?([01])\)?', lambda m:m[1]+('true' if m[2]=='1' else 'false'), s)
        s = re.sub(r'("'+b+r'"\s*=\s*)([01])\b', lambda m:m[1]+('true' if m[2]=='1' else 'false'), s)
    return s

tables = []
indexes = []
foreign = []
triggers = []
for f in sorted(root.glob('*/Tables/*.sql')):
    s = convert(f.read_text(encoding='utf-8-sig'))
    # Delay cross-schema FKs until every table exists.
    for statement in re.split(r';\s*', s):
        statement = statement.strip()
        if not statement: continue
        if 'CREATE TABLE' in statement:
            table = re.search(r'CREATE TABLE ("\w+"\."\w+")', statement)[1]
            lines = statement.splitlines()
            kept = []
            for line in lines:
                if 'FOREIGN KEY' in line:
                    foreign.append('ALTER TABLE '+table+' ADD '+line.strip().rstrip(',')+';')
                else: kept.append(line)
            statement = '\n'.join(kept)
            statement = re.sub(r',\s*\)$', '\n)', statement)
            tables.append(statement+';')
            if '"RowVersion"' in statement:
                triggers.append(f'CREATE TRIGGER row_version BEFORE INSERT OR UPDATE ON {table} FOR EACH ROW EXECUTE FUNCTION public.zrc_row_version();')
        else: indexes.append(statement+';')

schema = '\n'.join(f'CREATE SCHEMA IF NOT EXISTS "{s}";' for s in ['identity','nav','catalog','ordering','customers','engagement','content','reporting'])
schema += "\nCREATE FUNCTION public.zrc_row_version() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN NEW.\"RowVersion\" := decode(replace(gen_random_uuid()::text, '-', ''), 'hex'); RETURN NEW; END $$;\n"
schema += '\n\n'.join(tables+foreign+indexes+triggers)
for f in sorted(root.glob('*/Views/*.sql')):
    if f.stem == 'vw_KitchenPrep':
        schema += '''\nCREATE VIEW "ordering"."vw_KitchenPrep" AS
SELECT o."EventDate", j.value AS "ItemName", COALESCE(o."VariantName", 'Standard') AS "VariantName",
 SUM(o."Guests")::integer AS "TotalHeads", COUNT(*) AS "OrderCount"
FROM "ordering"."Orders" o
CROSS JOIN LATERAL jsonb_array_elements_text(o."SnapshotJson"::jsonb->'items') j(value)
WHERE o."Status" IN ('Confirmed','InPreparation')
GROUP BY o."EventDate", j.value, o."VariantName";\n'''
    elif f.stem == 'vw_OrderSummary':
        schema += '''\nCREATE VIEW "reporting"."vw_OrderSummary" AS
SELECT "Id", "OrderNo", "EventDate", "Status", "PackageName", "CategoryName", "Guests",
 "GrandTotal", "TotalCost", "GrandTotal"-"TotalCost" AS "Profit",
 COALESCE((SELECT SUM(p."Amount") FROM "ordering"."Payments" p WHERE p."OrderId"=o."Id"),0) AS "PaidAmount"
FROM "ordering"."Orders" o;\n'''
    else: schema += '\n'+convert(f.read_text(encoding='utf-8-sig'))

def seed(s):
    s = convert(s)
    # PostgreSQL VALUES sources infer integer flags: cast them at their use sites.
    for b in bools: s = s.replace('s."'+b+'"', '(s."'+b+'"::integer <> 0)')
    s = s.replace('VALUES (gen_random_uuid(),', 'VALUES (gen_random_uuid()::text,')
    s = re.sub(r'DELETE (\w+) FROM ("\w+"\."\w+") \1\s+JOIN ("\w+"\."\w+") (\w+) ON (.*?) WHERE ',
        r'DELETE FROM \2 \1 USING \3 \4 WHERE \5 AND ', s, flags=re.S)
    s = s.replace('DELETE t FROM "identity"."RolePermissions" t', 'DELETE FROM "identity"."RolePermissions" t')
    # Unquoted alias columns in the role grants are consistently lower-case.
    s = s.replace('s."RoleId"', 's.roleid').replace('s."PermissionId"', 's.permissionid')
    s = s.replace('t.RoleId', 't."RoleId"').replace('t.PermissionId', 't."PermissionId"')
    s = s.replace('UPDATE c SET "ParentId" = p."Id"\nFROM "nav"."MenuItems" c JOIN "nav"."MenuItems" p\n  ON ',
        'UPDATE "nav"."MenuItems" c SET "ParentId" = p."Id"\nFROM "nav"."MenuItems" p\nWHERE ')
    s = s.replace('WHERE c."ParentId" IS NULL', 'AND c."ParentId" IS NULL')
    # Only direct INSERT flags (variant rows) remain integer literals.
    s = re.sub(r"('Chicken', 0\.00, 0, )1", r'\1true', s)
    s = re.sub(r"('Mutton', 80\.00, 0, )0", r'\1false', s)
    return s

seeds = '\n'.join(seed((root/'Scripts/Seed'/f).read_text(encoding='utf-8-sig')) for f in ['Permissions.sql','Roles.sql','RolePermissions.sql','MenuItems.sql','Catalogue.sql'])
out.mkdir(exist_ok=True)
result = '-- Generated by database/postgresql/generate.py; review before deployment.\n'+schema+'\n'+seeds
(out/'001_initial.sql').write_text('\n'.join(line.rstrip() for line in result.splitlines())+'\n', encoding='utf-8')
print('Generated PostgreSQL initial schema and seeds.')
